src/mol.cpp
Z-ordering let's you terminate early if the z dimension is beyond
a cutoff.  However, the code was using the radii of the two current
atoms to determine when to terminate.  The caused problems when
one or more of the atoms were a hydrogen with a small radii.
In this case, the search terminated to early and bonds were missed.
Here's an example that fails:
ATOM    559  N   MET    38       4.134  38.514 132.609  1.00  0.00           N
ATOM    560  CA  MET    38       5.261  38.734 131.692  1.00  0.00           C
ATOM    561  C   MET    38       4.788  38.782 130.238  1.00  0.00           C
ATOM    562  O   MET    38       5.354  39.502 129.410  1.00  0.00           O
ATOM    563  CB  MET    38       6.357  37.679 131.847  1.00  0.00           C
ATOM    564  CG  MET    38       7.317  37.906 …
=> Fix problem with ConnectTheDots and z-ordering.

CMakeLists.txt
We need to add matching flags to link any c files in the library (in inchi code) on visual studio.
=> Allow static compilation of inchi (.c) files

src/formats/CMakeLists.txt
in gamessuk <regex> can be used for windows, but this file uses
features not present in this version.
=> Make orca require REGEX_H (unix like)

scripts/python/pybel.py
As simple as in title.
I was thinking of implementing other GENOPTIONS, like -f, -l in pybel. I think it would be better and more user-friendly when pybel.readfile() would have explicit arguments: pybel.readfile(....., first=None, last=None). Ideas?
=> Check for gz in extension and compress output if necessary

src/formats/mmcifformat.cpp
This was left out by the earlier commit while using mmcif as default
plugin for cif files.
=> Separate charge from symbol to derive the atomic number

CMakeLists.txt, data/CMakeLists.txt, doc/CMakeLists.txt
This allows installing the architecture independent data outside
the prefix, for example on a multiarch layout where the prefix
is /usr/{host-triplet}.
=> CMakeLists.txt: Allow configuring BABEL_DATADIR

src/depict/depict.cpp
Fixed an error with the allExplicit option where the function was opposite to what was stated. Fixed by removing the negation in test.
See line note in  https://github.com/openbabel/openbabel/commit/ba397aa5a01cd3753072fadf9535d0092dfcf784#diff-2a365bc04bfc2f8bea760bcade7466a0
=> Fixed an error with the allExplicit option

include/openbabel/inchiformat.h, src/formats/inchiformat.cpp, src/formats/smilesformat.cpp, src/ops/unique.cpp, test/CMakeLists.txt, test/regressionstest.cpp
(1) Don't cache inchi when generating inchifield smiles
(2) Don't use cached inchi if the user specifies one of several InChI output options
(3) Add a new test file for caching (and debugging) regressions: regressionstest.cpp
(4) Drive-by fix for typo in docstrings for 'unique' op and inchiformat ("/sp3" -> "/nosp3")
(5) Add test for regression to regressionstest.cpp
=> Fixes #135

src/formats/pdbqtformat.cpp
Added two new options to the PDBQT writing code:
-h to preserve hydrogens 
-n to preserve atom and residue naming
These are useful to simplify the integration of Vina/autodock with other tools.
=> Add PDBQT options to preserve hydrogens and preserve atom naming

src/math/vector3.cpp
What should be a lightweight operation (create random vector) was allocating and deallocating memory unnecessarily.
=> don't create a new obrandom everytime a random vector is desired

scripts/python/pybel.py
I've had imolecule on pypi for a while, and it makes more sense to maintain that and require users to `pip install imolecule` when they want the integration. Switching moves this rendering to the most recent version, which includes things like:
* Fallback to canvas rendering for users without webgl
* Only renders on change
* High-DPI screen bugfixes
* Highlight support ([info](https://github.com/patrickfuller/imolecule/pull/7))
* Now uses lambert renderer instead of toon
Most of these updates come from @bjonnh, so kudos go to him.
=> 3D ipython rendering moved to pip-installable library

include/openbabel/plugin.h, src/plugin.cpp
Hi,
The "charges none" method seems to have been removed at some point.
I'd like to re-introduce it, as we have a dependency on it.
Matt
=> Reintroduce the 'charges none' method

CMakeLists.txt, src/formats/CMakeLists.txt
For MSVC, link against a DLL rather than compiling it in. The latter was
causing a link error which I could not resolve. Fixes #151
=> Fix for failure to build JSON formats with MSVC.

include/openbabel/plugin.h, src/formats/CMakeLists.txt, src/formats/formats.cmake, src/formats/stlformat.cpp, src/plugin.cpp
Hidden surfaces not culled, but Makerware seems happy with it.
No control over # of triangles
CPK colours optional 
I'm making this a separate plugin to pointcloud, as it works in quite a different way, and I expect will attract more features over time (eg adding bonds for CPK/molymod style prints)
=> New plugin: STL output of VDW surface

src/ops/conformer.cpp
The fix is for a simple string-to-integer function where it was mistakenly coercing a istringstream to a boolean, but MSVC 2013 no longer is happy with this.
=> Fix for compile error with MSVC 2013.

src/charges/eqeq.cpp, src/charges/qeq.cpp, src/charges/qtpie.cpp
Fix MSVC2013 build problems as the erfc/erf are now available and this causes the compiler some confusion.
=> Edit ifdef MSVC to be MSVC version specific

include/openbabel/obutil.h
OBStopwatch was using integer division to arrive at a double,
and so would report only integer seconds.
=> Fix the OBStopwatch

test/testfastsearch.py
I break the -at option in a local build, and make test failed to detect
the breakage.  Add a regression test for it.
=> Add regression test for fast tanimoto search

src/formats/fastsearchformat.cpp
Changing the stream precision to 0 seems like a bad idea.
I'd rather see a reported time of 90.5956 minutes and
mentally round it to the number of sig figs I think is
appropriate, than see 1e+02 minutes and be left to wonder
where between 50.1 and 149.9 that might mean.
=> Don't set precision to 0 when reporting time estimate

src/formats/vaspformat.cpp
The option allows to sort atom not alphabetically, but using the custom list. For example, an option -xw "Al Si O" force obabel to put Al atoms in a first in the output POSCAR file, next Si and in the end O atoms. The option is really useful if you have POTCAR file is already exists. The order of elements in both POSCAR and POTCAR files should be the same. The option is fully compatible with previous alphabetical implementation.
=> New option in VASP format. Custom atom sorting.

data/space-groups.txt
This was causing a problem with one of the cif file we ran. So I had to fix this to get the right space group. Otherwise the pdb file converted from cif get default to P1.
=> Fixed the (HM: 63 m c) to (HM: P 63 m c) in space group data file.

src/obconversion.cpp
More checks were necessary to make all occurrences
of zlib-dependent code build conditional.
=> Added further checks for zlib availability in OBConversion

.travis.yml
Travis uses 1.5 core per build machine. Most of the time, the build is
slowed by disk access, so setting -j2 to make usually speed up things a lot.
=> speed up travis builds

src/mol.cpp
previously all but the currently set conformers were blown away; now that they are kept around, SetConformer(0) is having an effect which is unexpected and breaks backwards compatibility
This change removes the call to SetConformer(0) so that addHydrogens no longer has the side effect of changing the currently selected conformer.
=> do not reset conformer in addH

src/depict/depict.cpp
Adds a small amount of time, but greatly improves the look
of the ball-and-stick depictions (i.e., atoms with + z coordinates
are in front of "behind" atoms).
=> Make sure to z-sort atoms for depictions.

src/formats/CMakeLists.txt, src/formats/outformat.cpp, src/formats/siestaformat.cpp, src/formats/vaspformat.cpp
It searches for a .STRUCT_OUT file since the output coordinates are usually put there, but it can read the coordinates from a .out file if the coordinates are there as well. Also made a small change to vaspformat.cpp so that 'babel -iPOSCAR <filename> -o<whatever>' will work properly.
=> Added basic reading for siesta output (.out) files.

scripts/python/setup.py
When installing the python bindings independently using `pip` or `python setup.py install`, distutils/setuptools now appear to add some default SWIG `include_dirs` and `library_dirs`, so we should append the openbabel paths to these lists rather than overwriting them entirely.
=> Fix swig include_dirs+library_dirs in setup.py

src/builder.cpp
This fixes a logic error in OBBuilder which led to nondeterministic behavior for some groups (e.g. carboxylate).
=> Builder fixes

src/formats/pqrformat.cpp
The **pqr** format reader ignore the last element column...
Use the atom radius data saved in general data, not the element radius.
=> Charge_Radius_Error

src/fingerprints/finger2.cpp
If the atom currently being visited in a path through the atoms can
both close a ring back to the first atom, and can also proceed
to a different atom, and the bond enumerator returns the closing
bond first, then the other path was omitted.  That is because after
the path was marked as closed and the ring added to the fingerprint
bit set, the closure is not cleared.  When the next bond is visited,
the path is not added because it still appears to be closed.
In order for the bit to be missed altogether, this problem must
occur in both directions along the path, so the situation is somewhat
rare.
See bug #206
=> Fix bug in the fingerprint algorithm.

include/libxml/xmlexports.h, src/fingerprint.cpp, test/CMakeLists.txt
include/libxml/xmlexports.h: CMake no longer defines _WIN32 under Cygwin. 
src/fingerprint.cpp: likely a typo -- "__CYGWIN32__" is not defined.
test/CMakeLists.txt: need to include "include(UsePythonTest)" before using ADD_PYTHON_TEST.
=> Fix compiling errors under Windows & Cygwin

include/openbabel/plugin.h, src/formats/fastsearchformat.cpp, tools/babel.cpp
This fixes a segfault when trying to use a fastsearch index
babel mymols.fs -ifs -sN#Cc1ccccc1C#N results.smi
would segfault since the fastsearch plugin assumed that the -s argument was set and was indexing into an empty vector.  If it encounters this situation it will now generate a message instead.
More importantly, the reason the argument was missing is because plugin parameter options were getting registered *after* the parameters were parsed in babel.cpp.  Specifically, in DoOption in babel.cpp `nParams` for -s was zero since its number of arguments hadn't been registered yet. This is due to the commit 3cb13fb2155740ad632c0cd49fcbf9686c78f2ee.  This made plugin loading something that happens greedily when the first plugin is retrieved, whereas before it happened in the OBConversion …
=> fix for segfaulting similarity search with fastsearch index

include/openbabel/atom.h, src/atom.cpp
The new OBAtom:IsHbondAcceptor() method should provide a more fine-grained detection of hydrogen bond capabilities of atoms, basing on their neighbors (i.e., different chemical moieties are recognized). The rules are based on references from Kubyni and others, and the result can differ significantly from the current 2.3.x implementation, especially for the oxygen atom. A legacy function (OBAtom:IsHBondAcceptorSimple()) has been created to provide some kind of backward compatibility. 
Accordingly to these rules, the function will return:
aliph-O-aliph ether   -> true   [1]
hydroxy O-sp3         -> true   [1]
aro-O-aliph ether     -> true   [1]
ester O-sp2           -> true   [1]
sulfate O (R-SO3)     -> true   [2]
sulfoxyde O (R-SO-R)  -> true   [2]
organoboron-F (R-BF3) -> true   [3] …
=> New OBAtom:IsHbondAcceptor() method

src/charges/eem.cpp
In a previous commit, the type of the variable i was changed from int to unsigned int. As a result, the back substitution loop became infinite (comparison of unsigned int with zero) and the arrays B and A were accessed beyond their bounds causing a segfault.
=> Fix infinite loop in eem calculation

src/formats/mmcifformat.cpp
In the case of setting the atom type from the atom label, this change allows for correctly parsing atom names containing digits:
loop_
_atom_site_label
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
H2A 0.4481 -0.8277 0.2649
H2B 0.6245 -0.7166 0.2599
H3A 0.4700 -0.6074 0.1979
H3B 0.3580 -0.7706 0.1862
Before that, digits were stripped ending up with the weird types: HA, HB, etc.
=> Fix mmcifformat.cpp to allow correctly setting atom types from the atom names containing digits

cmake/modules/UsePythonTest.cmake
Otherwise test build fails if Python interpreter is not found or is
unset.
=> cmake/modules/UsePythonTest.cmake: Pop policy on return

src/math/spacegroup.cpp
This needed in the cases like:
loop_
_symmetry_equiv_pos_site_id
_symmetry_equiv_pos_as_xyz
1 +X,+Y,+Z
2 -X,+Y,+Z
3 +X,1/2-Y,1/2+Z
4 -X,1/2-Y,1/2+Z
5 -X,-Y,-Z
6 +X,-Y,-Z
7 -X,1/2+Y,1/2-Z
8 +X,1/2+Y,1/2-Z
=> Make transformation parser case insensitive

src/math/spacegroup.cpp
This fixes the issue with reading space groups from PDB (and maybe other formats).
=> Clean space group name before anything

src/math/spacegroup.cpp
This should match the correct space group when the same transformation is present:
```
_symmetry_equiv_pos_as_xyz
x,y,z
x,y,z
```
=> Allow only unique symmetry transformations

src/formats/gaussformat.cpp
The total charge in an OBMol may be changed by EndModify or
other routines involved with changing bondorder and or atom types.
This patch moves the assignment to the end of the file to make
sure the total charge does not get lost.
=> Moved storing total charge in gaussformat.cpp

src/dlhandler_unix.cpp
The Windows equivalent returns 0 for error/no files, this variant should
do the same. This member is used to load all plugins, and can result in
an infinite loop when -1 is returned.
=> The findFiles member should return 0 for error

data/phmodel.txt
The change fixes a bug that fragmented the molecule when processing the azide group.
The original patterns `[ND1:1]=[ND2:2]=A` used only two nitrogens, resulting probably in ambiguous matches:
`N=NNCCN >> [N-]=[NH2+].CC[NH3+]`
The new patterns addresses the issue and prevents the fragmentation of the molecule.
`N=NNCCN >> [N-]=[N+]=NCC[NH3+]`
Now also inorganic azide is recognized.
=> Modified phmodel.txt to fix azide transformation

CMakeLists.txt
Default the OPTIMIZE_NATIVE option to OFF, and update the documentation
to more accurately reflect the optimization for the machines CPU
architecture. This isn't related to cross-compiling, so replaced
references to it.
=> Default OPTIMIZE_NATIVE to OFF, fixes #279

CMakeLists.txt
The main improvement is getting rid of the hard-coded path by using the already-existing variable.
(Also introduces the possibility of the include install path to something else using -DOB_INCLUDE_DIRS in cmake; this was my personal reason for looking through and editing the CMakeLists.txt file, I wanted the option to install headers to ~/include/openbabel/ instead of ~/include/openbabel-2.0/openbabel/, for example.)
=> CMakeLists.txt fix for wrongly hard-coded path

src/formats/vaspformat.cpp
According to the POSCAR file description at http://cms.mpi.univie.ac.at/vasp/vasp/POSCAR_file.html: "The second line provides a universal scaling factor ('lattice constant'), which is used to scale all lattice vectors and all atomic coordinates." When using Cartesian coordinates, we need to scale the coordinates of the atoms with the scaling factor.
=> Fixed a problem with reading POSCARs.

tools/obdistgen.cpp, tools/obenergy.cpp, tools/obgen.cpp, tools/obgrep.cpp, tools/obminimize.cpp, tools/obmm.cpp, tools/obprobe.cpp, tools/obprop.cpp, tools/obsym.cpp, tools/obtautomer.cpp
Well-behaved programs are supposed to exit with status 0 upon
successful completion. Make obtautomer follow this convention.
There are other programs which exit with 1 upon successful completion,
such as obprop, obsym, obprobe and perhaps others.  But since they
have been released in that state, maybe it is better not to change
them now.
=> Make obtautomer exit with status 0 on success

src/data.cpp, src/forcefields/forcefieldmm2.cpp, src/formats/libinchi/ichi_bns.c, src/formats/libinchi/ichimake.c, src/formats/mdffformat.cpp, src/formats/mol2format.cpp
[src/data.cpp:108]: (error) Width 4 given in format string (no. 2) is larger than destination buffer 'symbol[4]', use %3s to prevent overflowing it.
[src/forcefields/forcefieldmm2.cpp:496]: (style) 'operator=' should return reference to 'this' instance.
[src/forcefields/forcefieldmm2.cpp:354]: (style) Unused variable: idx
[src/forcefields/forcefieldmm2.cpp:519]: (style) Unused variable: filename
[src/forcefields/forcefieldmm2.cpp:520]: (style) Unused variable: currently_parsing
[src/formats/libinchi/ichi_bns.c:6018]: (warning) Size of pointer 'pNewVert' used instead of size of its data.
[src/formats/libinchi/ichi_bns.c:6071]: (warning) Size of pointer 'pNewVert' used instead of size of its data.
[src/formats/libinchi/ichi_bns.c:9614]: (error) Expression 'pBond.cap=pBond.flow=pBond.cap=0' …
=> cppcheck: fix some reports

src/forcefields/forcefielduff.cpp, src/forcefields/forcefielduff.h
I noticed slight differences in the FF calculation results for repeated calculations of the same structure using UFF. The error stems from a missing SetupPointers() override.
gaff, ghemical, mmff94 all use OBFFCalculation objects and override the forcefield base function SetupPointers() to assure that the coordinate pointers are setup properly. The patch fixes the error, such that repeated calculations lead to the same results.
=> UFF forcefield: fix missing SetupPointers()

tools/babel.cpp
For "babel -H", the warning is added near the top of the help text
For "babel" just on its own, the warning is added at the end of the short usage information.
For other uses, no warning is given.
The text is:
<pre>
WARNING: babel is deprecated and will be removed in a future release
of Open Babel. You should use obabel instead. For information
on the differences please see:
http://openbabel.org/docs/current/Command-line_tools
</pre>
=> Add deprecation warning for babel

include/openbabel/atom.h, src/atom.cpp
I think that OBAtom::IsSulfoneOxygen should not be added to the public API. It is currently used as a helper function by IsHBondAcceptor.
=> Remove OBAtom::IsSulfoneOxygen from the public API

include/openbabel/atom.h, src/atom.cpp, src/formats/mol2format.cpp
I've moved OBAtom::IsThiocarboxylSulfur to being a helper function in MOL2
=> Remove OBAtom::IsThiocarboxylSulfur from the public API

include/openbabel/bond.h, src/bond.cpp, src/formats/pdbqtformat.cpp
These functions are used by pdbqtformat.cpp in the context of determining whether a bond is rotatable.
=> Remove OBBond::IsAmidine and IsImide from public API

scripts/openbabel-R.i, scripts/openbabel-java.i, scripts/openbabel-mono.i, scripts/openbabel-perl.i, scripts/openbabel-php.i, scripts/openbabel-python.i, scripts/openbabel-ruby.i
Swig uses C style comments. Earlier I was using "#" sometimes which now causes a Swig error. Another dev had changed a few of these to %#. I have changed everything to //.
=> Fix comment symbol in swig interfaces

src/forcefield.cpp
The WeightedRotorSearch method of the OBForceField class returned wrong
index to the conformer of the lowest energy.  Although the method worked
correctly, it returned incorrect result. I think this must be somehow
related to a change in indexing conformers which did not propagate fully
to dependent classes. The change is minimal.
=> Fix in OBForceField::WeightedRotorSearch.

include/openbabel/mol.h, src/mol.cpp, tools/obprop.cpp
For assessing ligand flexibility, counting rotors within rings is highly undesirable.  This patch restores the old behavior of NumRotors and makes the new behavior available with a boolean argument.
Internally, there don't appear to be any dependences in NumRotors, so restoring the old behavior will probably keep the most people happy.
=> restore NumRotors behavior and add rotor count output to obprop

src/formats/mdlformat.cpp
The original code added the same PairData a second time if there was an existing ASCII depiction
=> Fix for logic when there is an existing ASCII depiction in an SD file

src/formats/mdlformat.cpp
The default aspect ratio of 1.5 (set selfishly to suit the Windows command prompt) is likely to produce elongated structures when viewing SD files in an editor so I'm setting the ratio to 2.0 here.
=> Set the aspect ratio to 2.0 for ASCII depictions in SD files

src/formats/pdbformat.cpp
Bugfix for multi-model PDB writing. Previous versions inserted an
'END' tag before the 'ENDMDL' tag after each model. This violates
the PDB spec, which says 'END' marks the end of file, and also
trips up some programs/APIs (e.g. rdkit) that follow the spec and
stop reading the resulting PDB files after the first model.
Minimally invasive fix. I can make a test if desired.
=> Bugfix for multi-model PDB writing

src/ops/fillUC.cpp
If pOptions is not NULL but no transforms are found, then
the SpaceGroup object (spacegroup) will contain nothing. This commit adds
a check so that pSG gets set to pUC->GetSpaceGroup() when pOptions is not
NULL but there are no transformations. Because of C++ short-circuits in
operators such as &&, we know that pOptions->find() will never be called
if pOptions is NULL.
=> Fixed a bug with using the --fillUC feature

scripts/python/setup.py
This commit contains a few minor changes to the Python setup.py file that is used for independent installation of the Python bindings.
- Version bumped to 2.4.0 to match the main Open Babel version.
- The custom install command subclass was fixed to just call the superclass install method after the extra build_ext command. This resolved an issue with running bdist_wheel.
- `zip_safe` changed to `False`, so running `python setup.py install` behaviour is more like `pip install openbabel`.
=> Python setup.py fixes for 2.4.0 release

src/CMakeLists.txt
I'm not entirely sure, but I suppose this check for ZLIB availability is necessary.
Otherwise, CMake throws an error due to missing variable 'ZLIB_LIBRARY'.
=> Fix for missing ZLIB on win32

CMakeLists.txt
Previously the default build type was Release with debug info. This massively inflated the size of the compiled library (in particular the plugins).
Previously, the Release build had the -O2 switch.
=> Change default build type to RELEASE and add -O3 switch

src/ops/opconfab.cpp
If you don't include the original coordinates, confab currently will give you no conformers for molecule with zero rotatable bonds, so the molecule disappears from the output file. This makes confab return the original coordinates if there are zero rotatable bonds.
=> Include original when there are zero rotatable bonds in confab

include/openbabel/conformersearch.h, src/conformersearch.cpp, src/ops/conformer.cpp
When performing conformer searches on large molecules, it might be beneficial to a) fix certain rotors so that they are not changed and b) make the steric overlap filter less stringent. I made both changes available to the command-line interface.
I also noticed that the help message said a switch were called "--converge" but the code actually expects "--convergence". It also sometimes happens that none of the initial conformers pass the filter and the programme would then run indefinitely. Those bugs are also fixed.
=> add support for customizations of filter and rotors used during conformer search and small bugfixes

data/CMakeLists.txt
A fix for my merge of pull request #1545  which caused "make install" to fail as aromatic.txt was no longer present
=> Don't try to install aromatic.txt as it is no longer present

src/formats/gaussformat.cpp
OBMol::ConnectTheDots() kills conformer data.
Hat tip to Adrian Roitberg for reporting the bug via Avogadro.
=> Make sure to add conformers *after* performing bond perception.

src/formats/gaussformat.cpp
Fixes bug in previous commit - bonds were not perceived because no atom coordinates existed.
=> Set default coordinates before doing bond perception.

scripts/CMakeLists.txt
The DLFCN module has been removed from python 3.6, as it is not
documented. Same funtionality can be achive with the os module
that makes available the os.RTLD_GLOBAL variable for dlopen()
=> Fix bug #368: Python3.6 openbabel: No module named 'DLFCN'

src/formats/nwchemformat.cpp
This may or may not fix issue #1555, but I noticed it results in an unallocated pointer being freed, crashing the program.
Details:
When from_scratch is true, coordinates is not allocated. A separate if
statement was added to handle the case when from_scratch is true that
does not try to free coordinates.
=> Remove delete statement.

test/testpdbformat.py
I'm trying to write a package for Open Babel for the Spack package manager (see https://github.com/LLNL/spack/pull/4256). The installation seems to work, but one of the unit tests crashes:
```
Start 157: pytest_pdbformat
157/160 Test #157: pytest_pdbformat .................***Failed    0.04 sec
/blues/gpfs/home/software/spack-0.10.0/var/spack/stage/openbabel-2.4.1-g7kl4coxcxba2x2ugjpqbeipuembkpk7/openbabel-2.4.1/scripts/python:/scratch/ajstewart/spack-stage/spack-stage-z0O89Y/openbabel-2.4.1/spack-build/lib
File "/blues/gpfs/home/software/spack-0.10.0/var/spack/stage/openbabel-2.4.1-g7kl4coxcxba2x2ugjpqbeipuembkpk7/openbabel-2.4.1/test/testpdbformat.py", line 32
self.entryPDBwithInsertioncodes="""ATOM    406  N   VAL L  29      58.041  17.797  48.254  1.00  0.00           N  
^
TabError: …
```
=> Convert tabs to spaces in testpdbformat.py

src/forcefields/forcefieldmmff94.cpp, src/formats/mol2format.cpp
regression from 624abd353f8ea2c889edb663adf84e50ee81e8d2 (2008-03-06)
- if (atoi(nbr->GetType()) == 77)
+ if (type == 77)
whereas:
+ int type = atoi(atom->GetType());
cppcheck:
[src/formats/mol2format.cpp:49]: (style) Statements following return, break, continue, goto or throw will never be executed
=> Fix regression + minor cppcheck report

src/formats/libinchi/CMakeLists.txt
When trying to build openbabel in a Conda environment for [Bioconda](https://bioconda.github.io/), I got this error:
```
[ 11%] Linking C shared library ../../../lib/libinchi.so
cd /usr/users/ga002/soranzon/miniconda3/conda-bld/2.4.1_1494426296543/work/openbabel-openbabel-2-4-1/src/formats/libinchi && /usr/users/ga002/soranzon/miniconda3/conda-bld/2.4.1_1494426296543/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/cmake -E cmake_link_script CMakeFiles/inchi.dir/link.txt --verbose=1
/usr/users/ga002/soranzon/miniconda3/conda-bld/2.4.1_1494426296543/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac …
```
=> Link libinchi with math library

src/mol.cpp, test/mol.cpp
Running GetFormula on molecules containing the heaviest elements
(atomic number > 110) could cause a segfault due to out of bounds
memory access.  Updated the alphabetized list of elements and added
bounds checking for the atomic number.
=> Fix segfault in OBMol::GetSpacedFormula

src/math/spacegroup.cpp
[src/math/spacegroup.cpp:434]: (style) Condition '1==0' is always false
commit 6d448d8a6967b5edca34ef0d7cef6466985b817c was:
math/spacegroup.cpp: Fix -Wparentheses
-        if ((m_OriginAlternative & 1 == 0) && (_SpaceGroups.sgbn[m_HM] == NULL))
+        if ((m_OriginAlternative & (1 == 0)) && (_SpaceGroups.sgbn[m_HM] == NULL))
but (1 == 0) doesn't mean anything.
the initial warning meant since "==" has more priority than "&" so there was a pb here
(see http://en.cppreference.com/w/cpp/language/operator_precedence)
=> cppcheck: Condition '1==0' is always false

src/depict/depict.cpp
A fix for #1584. Molecules are normally scaled by the average bond length, but for molecules without bonds (e.g. inorganic salts) the scale was always set to 1. This PR calculates the minimal distance between two atoms and uses that instead of average bond length. There might be better ways, but this fixed my issue.
=> Fix multifragment depiction

src/stereo/perception.cpp
Made TetStereoToWedgeHash handle negative scores for very unfavorable wedge/hash bonds. Fixes #1581.
=> Fix wedge/hash in cyclopropyl

test/CMakeLists.txt
I ran into an issue where overwriting my LD_LIBRARY_PATH causes most of the tests to fail.
=> Prepend to LD_LIBRARY_PATH instead of overwrite

src/atom.cpp, src/formats/smilesformat.cpp, src/kekulize.cpp, test/testbindings.py
Note: this pull request is on top of #1576, and should not be merged before that.
1. Removed calls to SetType() from the SMILES parser, as well as from OBAtom::SetIsotope
2. Changed ParseSimple and ParseComplex to (each) use a single switch statement, rather than a test for isupper() first of all
3. In ParseComplex, parse the isotopes more efficiently and tighten up their handling when reading/writing
The test cases I wrote flushed out a few issues which I fixed:
1. Parse 'new' elements (based on those present in elements.txt)
2. Parse aromatic [te] and [bH]
In passing, I removed the warnings about "Illegal aromatic element". We handle these elements without trouble (by analogy with C, N or O), and I think they might cause a user to simply uppercase the element in the SMILES, which would …
=> Improve performance of SMILES parser

src/conformersearch.cpp
Define isnan for older versions of MSVC. Kudos to Christoph Lassner for his blog post: https://www.christophlassner.de/collection-of-msvc-gcc-compatibility-tricks.html
=> Introduce std:isnan for older versions of MSVC

src/formats/mmcifformat.cpp, test/cifspacegrouptest.cpp, test/files/test02.nohall.cif
Currently only _symmetry_equiv_pos_as_xyz is parsed in mmcifformat, which is superseded by _space_group_symop_operation_xyz: http://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Isymmetry_equiv_pos_as_xyz.html
cifformat covers both names, so change is not needed there.
Added a test.
=> Parse _space_group_symop_operation_xyz in mmcif

src/formats/tinkerformat.cpp
Silicon is incorrectly assigned as Magnesium. 
It should be replaced with the only silicon type in the mm3 parameter list - #19 silane
https://dasher.wustl.edu/tinker/distribution/params/mm3.prm
=> Change silicon to correct MM3 atom type

src/formats/smilesformat.cpp, test/testbindings.py
Fix #1605. Forgot that GetValence() returns the degree not the valence. We really ought to do something about this.
=> Fix for calculating implicit H count when reading SMILES

src/formats/smilesformat.cpp, test/testbindings.py
My code was not quite right for determining the number of attached Hs to an aromatic atom in SMILES. I was special-casing lowercase c versus everything else. I've now got a one size fits all. Thanks again to @johnmay for pointing out the issue with 'cn' and the solution.
=> Tweak the handling of implicit Hs when reading SMILES

src/obiter.cpp
For a molecule with no bond, or no atoms, the various iterators spend a fraction of a second allocating a visit array from 0 to -1 which is 2**32 or so. This effect can be observed for:
obabel -:C -omol
as it visibly pauses after writing the header.
The fix is simply to remove the no-op "return" to the start of the iterator ctors.
=> Fix underflow causing a noticeable delay when e.g. writing a molfile

data/CMakeLists.txt
Fixes a minor installation regression from PR #1601.  `make install` crashed with the following error:
```
CMake Error at data/cmake_install.cmake:39 (file):
file INSTALL cannot find
"/cygdrive/c/Users/Benjamin/Git/Contrib/openbabel/data/element.txt".
Call Stack (most recent call first):
cmake_install.cmake:68 (include)
```
Removing the deleted files from the cmake target allowed installation to proceed.
I haven't used Travis much yet, but would a `make install` test in CI be useful?
=> Fix install regression with element data

src/bitvec.cpp, src/fingerprint.cpp, src/kekulize.cpp, src/math/matrix3x3.cpp, src/obutil.cpp, src/parsmart.cpp, src/rand.cpp
Fixes issues preventing compilation with C++17 standard.
Two changes are made: register keywords are removed
and an implicit cast in a switch is made explicit.
=> Changes needed to compile with C++17

scripts/openbabel-csharp.i
the functions for OBTorsionIter and OBRingIter are misspelled in the swig interface file for the csharp bindings
=>  Fix some small misspellings in the csharp bindings

src/formats/tinkerformat.cpp
MM3 has an atom type definition specifically for carboxyl oxygens. The present code defines carboxyl oxygens as carboxylate ions (which remains the best choice when using MM2).
=> Correct MM3 carboxyl oxygen atom type definition

src/formats/siestaformat.cpp
=> For SIESTA format, use obErrorLog instead of cerr

src/kekulize.cpp
This is to a tweak to #1619 where the problem was in my kekulize code. The "-1" causing the problem has been removed, as it wasn't correct - it could never be -1.
=> Remove erroneous -1 in switch statement

src/formats/mopacformat.cpp
If the OBMol has a total charge, make sure that's passed along to the keywords line by default.
Improves batch processing files (e.g., singlet cations and anions).
=> Make sure to handle molecular total charge by default for keywords

src/depict/depict.cpp, src/formats/mdlformat.cpp, test/testbindings.py
This is a follow-on from the work on implicit hydrogens. In the end no changes were made to the data structures used to store information, but the handling of the existing file formats has been tweaked.
Storing undervalent atoms in MOL files now uses the valence field, rather than M RAD. M RAD is only used if a spin has been specified.
Now reading undervalent atoms from SMILES does not set the spin (it did previously). For depiction, changes were needed to ensure that radical dots were depicted in the same situations as before (by testing for either spin or undervalence).
=> Handle undervalent atoms and radicals in Mol files and Smiles

src/kekulize.cpp
When running over the whole of ChEMBL I found a segfault due to the path-so-far not being reset to empty. This could be triggered if needing to do multiple backtracks.
=> Reset path to empty in kekulization code (potential segfault)

scripts/python/Examples.html
Clarified required use of OBMol object:
While running the code as given originally would work, the repeated `import openbabel` made it seem that the second and third examples would work independently when in fact they won't without defining `mol = openbabel.OBMol()`.
=> Clarify python examples

src/fingerprints/fingerecfp.cpp
a) The ECFP implementation was expecting the ``std::vector<int>`` to be treated as a list of hashes whilst the callers were expected it to be a bit set. Whilst return the raw hash values is useful it would require a new API point.
b) Resolves #1651
With these changes the fingerprint scores 76.2% on the Briem Lessel benchmark. 
Also looks like the ``Fold()`` function is doing the wrong thing elsewhere too. For example if I generate MACCS keys...
```
0000000000021000014416cf1be5b083ad2fef7f1f	204
0004200000000021418004afa160b00910a1e46a1b	205
8004040000100200000816cf8d69b847856dfefb19	206
000000002000002141d034e82b61b08b01230d2d1f	207
00000000204000840194b1091b73b3e781eb2fff1f	208
```
and then fold them to say 256 bits... one would expect the output to be padded with trailing zeros
``` …
```
=> ECFP Fixup

include/openbabel/reaction.h, src/formats/rsmiformat.cpp, src/obmolecformat.cpp
Add support for multiple agents in OBReaction. This opens the way for implementing RInChI, for example.
=> Allow multiple agents in OBReaction

src/formats/rxnformat.cpp, test/testbabel.py
BIOVIA have started supporting agents in RXN file format. This may be due to the fact that ChemAxon (and NextMove) have been doing it for a number of years.
I've added read and write support for agents. On write, there are a number of options so that if you need to deal with an old version of BIOVIA you can ignore the agents or treat them some other way.
The following should now work:
```
obabel -irsmi -:"C>N>O" -orxn
```
We should generate 2D coordinates for --gen2D (but we don't). This will come automatically if/when we move to an overlay for reactions, so I'm not going to worry about supporting it now.
=> Add support for agents to RXN file format

src/formats/xsfformat.cpp
This is from the [official definition of XSF format](http://www.xcrysden.org/doc/XSF.html#__toc__3):
> An entry for an atom looks like:
>  AtNum   X Y Z
> where AtNum stands for atomic number (or symbol), while X Y Z are
> Cartesian coordinates in ANGSTROMS units. Here is one example: # Please
> enter the commit message for your changes. Lines starting
=> Fix reading atom symbols from XSF file

src/formats/json/pubchemjsonformat.cpp, test/CMakeLists.txt, test/testpcjsonformat.py
At some point in the past, it seems that the PubChem JSON format returned by the PubChem REST API changed to return enum type names as integers instead of the string representation. So elements are atomic numbers instead of symbols, bond orders are integers instead of "single", "double", etc.
[Discussion on openbabel-devel mailing list](https://sourceforge.net/p/openbabel/mailman/message/35918486/)
=> Fix pubchem JSON handling of enum types as ints

scripts/perl/MANIFEST, scripts/perl/Makefile.PL
The MANIFEST file has openbabel-perl.cpp spelled with
an underscore rather than a dash.  This causes a
confusing but otherwise harmless warning when running
`perl Makefile.PL`.
=> Correct spelling of file name for Perl bindings

scripts/openbabel-python.i
A recent API change (#1576) broke FragIt (https://github.com/FragIt/fragit-main) which depended on the knowledge about implicit bonds. Now, #1576 did include new utility functions (obfunctions.h) but these functions were never exposed through the python API.
1. This PR exposes those functions hidden away in obfunctions.h so I can use them in FragIt
This PR does not add or remove anything in the API apart from exposing functionality in the API through the python-bindings but I am unsure whether I am required to add some form of test or other documentation?
=> Expose obfunctions api through python bindings

include/openbabel/atomclass.h, src/mol.cpp, test/testbindings.py
To begin with, this PR addresses the following bugs:
1. Atom maps were not being updated when atoms/hydrogens were deleted
2. Atom maps were not being copied on adding two molecules together
It also changes the behaviour of the OBAtomClassData somewhat:
1. If an atom does not have any class, the value of 0 is returned (instead of -9999)
2. Setting a value of zero removes the value
3. It is not enforced, but the documentation now states that atom classes can only be positive integers in keeping with the Open Smiles spec (previously it was documented as allowing any integer)
While these changes make the library work as expected, I plan to submit an Enhancement Proposal to suggest that we either use AtomIds to store this data (instead of AtomIdxs), or store it directly on the OBAtoms …
=> Correct handling of atom maps

src/formats/smilesformat.cpp, test/testbindings.py
This PR makes SMILES writing fast.
The main speedup was to avoid regenerating an OBStereoFacade each time we needed to look up a single atom. This was occurring in multiple places. Now a single OBStereoFacade is used for the molecule.
Also, I have removed all uses of strcpy, strlen and strcat.
There is some room for further speedups but I might move onto other stuff for now.
=> Speed up the SMILES writer

src/obmolecformat.cpp
Remove some audit messages that copy the entire format description and then substring it.
For smi->smi conversion, 1.6% of the total conversion time was spent on one of these audit message blocks, the majority of which on the string copy of the format description (which is not small for SMILES).
Since the other ones are similar, why not remove all three? Actually, I would remove all audit and debug level logging statements throughout the library (I have never used them for debugging), so I have no qualms about removing these three. They could be rewritten to avoid the string copy, but... What do they think?
=> Remove some audit messages

src/formats/smilesformat.cpp
3.5% of the time for SMI->SMI conversion is spent on writing std::endl, which flushes the buffers. I've replaced it with just "\n" for non-Windows, and "\r\n" for Windows. Does this need a further 'ifdef' for the Mac @ghutchis?
I've also edited the code to have just a single write to the output file stream. I note in passing that GetTitle(), by default, seems to be doing more work than necessary (a job for another day).
=> Faster SMILES: Replace std::endl by "\n"

src/mol.cpp, src/ring.cpp, src/stereo/perception.cpp
ThrowError was taking a total of 1.9% of the time for smi->smi. This was mainly attributed to three log messages, all audits. I've added an 'if' statement to check the logger's output level before throwing the error. I think it would make sense for this to be an idiom throughout the library.
=> Avoid logging messages that are taking time

src/formats/smilesformat.cpp, test/testbindings.py
The change I've made is simply to remove the prescan for illegal characters as we shouldn't be scanning over the SMILES string twice. It's enough to do this in the parser.
I've moved the warning message into ParseSimple and ParseComplex, but depending on the location of the illegal character, the parser will often just "return false;" without any warning message. The day will come when we improve the warning messages across the board, but that's not the focus of this PR, just to reduce the work we're doing.
=> When reading, don't pre-scan the SMILES string for illegal characters

src/mol.cpp, test/testbindings.py
When adding two molecules together via the += operator, any implicit ref in a stereo object was being set to atom id 0 instead of being preserved.
=> Fix bug when copying stereo during obmol += obmolB

src/formats/smilesformat.cpp, test/testbindings.py
Creating the SMILES atom order OBPairData was taking 10% of the time of SMI->SMI conversion. I rewrote it to avoid using stringstream and I made it optional.
=> Make generation of the SMILES atom order vector optional (Take 2)

src/formats/smilesformat.cpp, test/testbabel.py
So...I introduced some errors in ring closure parsing back in https://github.com/openbabel/openbabel/pull/1677. The ring closure numbers were not being read correctly for %NN or %(NNN).
For %NNN, I was not multiplying the existing value by 10 when adding the new digit.
For %NN, it was a bit more subtle:
```
digit = (*_ptr - '0') * 10 + *(++_ptr) - '0';
```
Can you see the problem? It's A = B + C - D, but sometimes C is evaluated before B. I don't usually increment pointers in expressions, but I made the mistake of doing it this time.
=> Fixes for ring closure parsing

src/formats/smilesformat.cpp
In the SMILES writer, the profiler showed IsOption() as talking up a percent or two. I've cached a few of the options in the functions highlighted by the profiler. Is it possible to persist some variables between repeated calls to the writer (or would this cause some threading issues) as this would be a potential improvement?
=> Minor speedup to avoid repeated calls to IsOption by caching some options

src/formats/smilesformat.cpp
This is an unneccessary string copy and its removal gives a 3% improvement in SMI->SMI conversion speed. 
There's one more string copy in ReadMolecule (a copy to split into smi+title), but this will more easily be dealt with once/if the handling of reactions is changed.
...and I think that's all the SMILES speed ups for now...
=> In the SMILES reader, avoid allocating a BUFSIZE buffer, and the associated string copy

include/openbabel/obfunctions.h, src/formats/smilesformat.cpp, src/obfunctions.cpp, test/testbindings.py
To test whether a double bond is implicitly cis (and thus requires no stereobond symbols), the original code used SSSR based ring perception. In fact, it always triggered it, even where the bond was not in a ring. Doh!
The replacement code does not use the SSSR.
=> Speed up SMILES writer by replacement of SSSR in SMILES writer with a bounded BFS

scripts/openbabel-python.i, test/testbindings.py
The generated bindings for the iterators included all of the methods of the underlying object (e.g. OBAtom), due to the -> operator. This is unnecessary in Python; by telling SWIG to ignore it, the total size of the bindings (the openbabel-python.cpp file) is reduced by ~20% without any loss in functionality.
=> In the Python bindings, avoid adding methods from the iterated object to the iterator itself

src/formats/smilesformat.cpp
Adding a few std::vector::reserve() made a measurable difference. In the profiler (with VS2017), this is attributed to _emplace_back.
Rewriting the parsing loop to be entirely switch-statement-based should be more efficient, but I didn't notice any speed-up.
=> Two minor SMILES speed improvements

data/phmodel.txt
This pull request changes the vinylogous carboxylic acid pH model. Originally, the pH model changed the resonance structure and put the charge at the O1 position (changing the bond order of the related atoms in the process). Due to the way openbabel applies the pH model, the model can be applied more than once resulting in an invalid structure. For example, if you add hydrogens to the [SDF file](http://www.rcsb.org/pdb/download/downloadLigandFiles.do?ligandIdList=CZA&structIdList=3FPB&instanceType=all&excludeUnobserved=false&includeHydrogens=false) for cyclopiazonic acid from the PDB 3fpb: `obabel -isdf CZA.sdf -omol2 -p 7.4` you can see that atom 3 has 5 bonds to it and oxygens 1 and 5 are both assigned negative charges. Additionally, in the output mol2 file the bond order for the bonds …
=> Remove the change in resonance structure from the vinylogous carboxylic acid pH model

src/atom.cpp
Previously, if the OBAtom was marked as a ring atom, then no ring perception was done, even where the rings were marked as unperceived. It should be the case that when a perceived property is marked as unset, that perception will always be triggered when queried.
I made a similar change recently for IsAromatic(), and it looks like there are more SSSR ring-related functions that may have the same problem.
=> Make sure that OBAtom::IsInRing always triggers ring perception if not set as perceived

src/mol.cpp
This fixes https://github.com/openbabel/openbabel/issues/340 .
I don't change the behavior if there is no contradiction between multiplicity and the number of electrons.
However, if there is contradiction (even number of electronic system with multiplicity 2, apparently it can't happen), we recalculate the spin multiplicity.
=> Fix wrong spin multiplicity assignment

src/formats/smilesformat.cpp
I rewrote the SMILES parsing loop to be entirely switch based. In theory it should be more efficient.
Although the diff looks big, it's a relatively minor change, but the indentation changed for the entire switch statement.
=> Moved more inside the switch statement for SMILES parsing

src/formats/vaspformat.cpp
This fixes #1676. The wrong variable name was used in the loop: should have been (*it), not atom. It would have been found by the original author if atom had been scoped a bit more tightly.
=> Fix error in VASPformat found by static code analysis

include/openbabel/generic.h, src/formats/gaussformat.cpp, src/generic.cpp
ESP is calculated once unless the Opt and Pop jobs are combined. In this case, ESP is calculated once before the geometry optmization and once after. If this happens, the second ESP must be added to OBMol.
=> Gaussformat reading electrostatic potentials

src/formats/xml/cmlformat.cpp, test/testbindings.py
Fix for #1731. Changes how atom class information is used in CML. CML doesn't itself provide a way to do this, so we hack it into the atomid. The existing code used a complex method, perhaps because of a belief that the atomid had to be letters followed by a number. Checking the CML spec, this doesn't appear to be the case. It just should be alphanumeric (or also underscore and minus), and unique within the molecule.
Given that, there's a very simple alternative; just append _ATOMCLASS to the end of the existing atomid. So what was "a3" for atom number 3, now might be a3_4 if that atom had atom class 4.
=> Fix for 1731. Store atom classes in CML atomids by appending _ATOMCLASS.

src/formats/gaussformat.cpp
Sometimes, Gaussian prints the numbers in a line such that they attached to each other with no space. So, tokenizing the line by space won't work properly. This happens for properties such as Exact polarizability printed in one line. e.x, Exact polarizability: 314.047-114.078 497.299  -0.000  -0.000 121.703
=> Reading Exact Polairzability from Gaussian log file

src/fingerprint.cpp
This was a bug found by the gcc warnings. It's the same as the one that bit me in #1723. In the expression:
```
if ( (a=((*ppat) & (*p++)) ^ (*ppat++)) ) break;
```
...the order of evaluation of *ppat and *ppat++ is undefined. Which means that our fingerprint screen may not have been working as intended for some users who compiled it (though I'm not aware of any complaints).
Actually, the rewrite should be slightly faster as the break now occurs before ppat and p are incremented.
=> Fix warning in fastsearch substructure fingerprint screen

src/formats/hinformat.cpp
I just found that the position of ifs.peek() is moved 1 character forward after ifs.tellg() called. And that's  the reason of issue #1569. Therefore I rewrote tail blank line removing codes to avoid use of ifs.peek().
=> Solving #1569

test/CMakeLists.txt
I'm not sure where this definition is even used? But this change appears to be necessary to compile when there is whitespace in the path to the Open Babel source directory.
=> Fix TESTDIR definition to allow space in path

src/forcefield.cpp
MSVC was warning:
```
1>C:\Tools\openbabel\baoilleach\src\forcefield.cpp(1344): warning C4267: '=': conversion from 'size_t' to 'char', possible loss of data
```
I added a cast to a char, which in the context seems to be fine.
=> Fix MSVC warning about type conversion

data/chemdrawcdx.h, include/chemdrawcdx.h
I am not sure if I am correct. But while implementing some more feature with ChemDraw CDX files, I found this one. 
The current value of `kCDXObj_Border` is `0x801a` which is the next value from `0x8019`, it should be `0x8020`.
=> Fix ChemDraw CDX incremental value

scripts/python/examples/testpybel.py, scripts/python/pybel.py
I wanted to generate molfile with 2d coordinates from SMILES and I was not able to do it in a nice way using pybel.
The only option I had was doing something like this:
from pybel import _operations
_operations['gen2D'].Do(mol.OBMol)
I think that would be nicer to have a mol.make2D() function.
=> add Molecule.make2D function

src/mol.cpp, test/testbindings.py
This is a fix for #1763. Calling OBMol.Separate() does not preserve atom order, but rather the DFS order of the atom iterator. It's a nice feature to preserve the original atom order, and it's something the user might expect.
=> Change the behavior of OBMol.Separate so that it preserves atom order

scripts/CMakeLists.txt, scripts/openbabel-python.i
Should have fixed this a long time ago. The DL flags kludge was needed for some platforms or else the plugins didn't load. I can't say whether it's still needed but at least now the code resets the flag value after forcing the plugins to load with OBPlugin::LoadAllPlugins().
I believe this fixes #917, #1222, and #1702. I can't reproduce the original problems though.
=> In the Python bindings, reset the DL open flags after importing _openbabel

include/openbabel/generic.h
On a 64-bit system, size_t must be bigger than int. Here I've added an explicit cast which keeps the original behavior; an alternative would be to return size_t directly.
=> Fix warning about size_t versus int cast

src/formats/smilesformat.cpp, src/formats/smilesvalence.h, test/testbindings.py
The original behavior of the toolkit is to write asterisk without brackets. This is the behavior of Daylight. The rewrite of the handling of implicit hydrogens caused them to be bracketed. 
This PR ensures returns to the original behavior, that asterisk is not bracketed unless necessary. This involved adding asterisk to the organic subset (with valence 0), and special-casing the handling of hypervalent "*" (as we now add square brackets around hypervalent atoms).
Also I got rid of a warning about unrealistic charge state for [*+] (triggered because the charge is greater than the atomic no).
=> Fix regression. Ensure that asterisk is unbracketed when writing a SMILES string

src/formats/smilesformat.cpp, test/testbindings.py
I finally got the AFL fuzz tester to work. This was on Linux with a static build.  The build failed when linking the obabel executable, but works if you do it manually after removing the "-rdynamic" from the VERBOSE=1 output.
Anyway, I ran it for a while (-ismi -onul) and fixed the segfaults it found:
1. SMILES starting with a bond symbol
2. Self-bonding through ring closures
3. Square planar and tetrahedral stereo with 5 nbors (where the nbor might be described by a ring closure)
Anything that's a reaction SMILES also segfaults if read as smi (I rejected these SMILES when testing), but hopefully we can fix this as described in my enhancement proposal.
I also tightened up the parsing of square planar stereo so that only @SP1/2/3 are accepted.
=> Fix SMILES parsing fuzz test failures from AFL

src/formats/gamessformat.cpp
This pull request is related to issue #1298 on which I have commented. The segfault was caused by line with symmetry of the mode like this one:
>       FREQUENCY:         2.93        1.88        0.55        0.35        0.16
>       SYMMETRY:          E           E           E           E           E
>       REDUCED MASS:      6.79503     6.40438    13.42881    10.66293     9.71937
The line was skipped by the program and the following loop did not read atoms correctly. The problem was apparently fixed in master, however fixing it exposes new segfault caused by the fact that `modeCount` variable is defined in line **548** as `unsigned int` and then used to leave the loop in lines **551-591**. At the end of loop there is a line
```
modeCount = vs.size() - 3;
```
For an empty vector the …
=> A small improvement of a bugfix solving segfault when reading GAMESS output with vibrations

src/formats/smilesformat.cpp, src/kekulize.cpp, test/testbindings.py
We should kekulize hypervalent N and S, especially as we write out the first one, and the second one occurs in SMILES strings generated by another toolkit.
This is a minor tidy-up based on the SMILES reading benchmark I put together.
=> Kekulize hypervalent aromatic N and S

src/formats/mdlformat.cpp, test/testbindings.py
The original code had an error where we were rounding to the "floor" rather than the nearest integer, which is the behavior of Biovia Draw. Also, the special cases of D and T were not handled as Biovia does, nor did we throw an error for out-of-range values (at least as described by ctfile.pdf).
=> Fix #1769 by correctly handling the mass difference field in MDL mol files

include/openbabel/atom.h, src/formats/moldenformat.cpp
Added methods to get and set the number of electrons cored by an electron core potential.
Molden files store an element via both the element symbol and the element number. If the element number is replaced by the actual charge (that not cored by an ECP), the number of cored electrons can be inferred directly from the file.
=> track the number of electrons cored by an electron core potential and read that information from Molden-files

src/mol.cpp, test/testbindings.py
It's an easy win to preserve whether aromaticity has been perceived when fragmenting a molecule. To do this, I also needed to make sure that this flag was maintained when copying a molecule via "=".
=> When calling OBMol.Separate, preserve whether aromaticity has been perceived

src/formats/pdbqtformat.cpp
When debugging #1790, I hit a segfault in debug build with MSVC due to running off the start of an iterator.
Note to self: we should really write up the best idiom for deleting a set of bonds.
=> Fix segfault due to running off the start of an iterator in PDBQT format

include/openbabel/residue.h, src/formats/mol2format.cpp, src/formats/pdbqtformat.cpp, src/residue.cpp
API change: return value changed from unsigned int to int to allow handling of potential negative values.
=> Fix 1786 by changing the return value of OBResidue::GetNum()

src/typer.cpp
This addresses the NaN occurring in OBBuilder (e.g., #1792)
because a hybridization might be 0 for a 'strange' atom, e.g.
FCl(=O)=O. As a fallback, assign a hybridization based on the
valence. Not sure it's ideal, but it's better than nothing.
=> Always ensure hybridization

scripts/CMakeLists.txt
Don’t link against python on the Mac, and use `-undefined dynamic_lookup` to allow this.
I think this is how to fix #1802
=>  Fix linking of python bindings

include/openbabel/conformersearch.h, src/conformersearch.cpp
Fixes #1761. See #1761 for background and the fix. Essentially the variables niche_radius and sigma_share in the GA are both supposed to be doubles and this fixes that.
=> Apply fixes from Benoit Leblanc to address int/double type warnings.

src/formats/gamessformat.cpp
See https://github.com/openbabel/openbabel/issues/1768#issuecomment-374051555
for bt and some explanations
=> Fix#1768: Segfault upon reading GAMESS outputs of DFTB3 calculations

src/builder.cpp
This pull request is related to #1662.
There is a case when the coordinates calculated by OBBuilder include NaN.
This PR raises a warning when there exists NaN in calculated coordinates.
This does not solve the issue completely, but raising a warning is necessary until it is fixed.
I show the result of the following code. 
```cpp
#include <iostream>
#include <string>
#include <sstream>
#include <openbabel/mol.h>
#include <openbabel/obconversion.h>
#include <openbabel/builder.h>
int main(int argc, char** argv){
std::string smiles = "FCl(=O)=O";
std::stringstream ss(smiles);
OpenBabel::OBConversion conv(&ss, &std::cout);
conv.SetInAndOutFormats("smi", "sdf");
OpenBabel::OBMol mol;
conv.Read(&mol);
OpenBabel::OBBuilder builder;
builder.Build(mol);
conv.Write(&mol);
}
```
Current result:
``` …
```
=> Raise a warning when coordinate is NaN

src/formats/adfformat.cpp, src/formats/outformat.cpp
These readers only read atom positions, the unit cell,
and the electronic energy.
They were also added to the generic "out" format so that
they can be automatically detected.
=> Added basic ADF Band and ADF DFTB readers

src/formats/xml/cdxmlformat.cpp
When converting from molfile to cdxml, stereo bonds conversion is in-correct.
This pull request fixes cdxml stereo bonds.
For example, `alanine.mol` is my source file; `alanine_ori.cdxml` is the conversion result from the current master; `alanine_fix.cdxml`  is the conversion result from the pull request.
[alanine.zip](https://github.com/openbabel/openbabel/files/1720262/alanine.zip)
=> fix cdxml stereo bonds

include/openbabel/mol.h
Mark that chains perception will be required. Toggling this flag is useful if copying a portion of an OBMol with OBMol::CopySubstructure (see #1811).
Personally, I think that all of these perception get/set/has functions should be removed and replaced with an enum, so that it would be UnsetFlag(ChainsPerceived). Or at the least, don't have an unset function, instead have SetChainsPerceived(false). It's silly to have three functions for every bit in an int. In the meanwhile, here's another one...
=> Add OBMol::SetChainsPerceived(false)

scripts/python/pybel.py
I'm using python2.7 and conda. Problem now: if i would install PIL (with conda), my versions of matplotlib and numpy would be downgaded. But for my project I need these new versions. I think the problem is that the latest version of PIL  is from 2009 and so there are these dependency problems.
I fixed that by using pillow (a PIL fork) instead of PIL. With pillow there are no dependency problems and so i can use the newest versions of matplotlib and pybel without to give up "the molecule drawing functionality".  :)
=> Using pillow instead of PIL

src/bond.cpp
All the other cerr statements should be taken into account.
Some should be changed by using error log, other should just
be removed
=> Fix#1056: remove a debug output

include/openbabel/mol.h, src/mol.cpp, test/testbindings.py
Here is an implementation of OBMol::CopySubstructure. It copies a substructure of a molecule to another one, and has a bunch of optional parameters that hopefully cover every possible use case (or at least, make it possible for the user to do so). OBMol::NextFragment() already had some of this code; I've taken it out and expanded it, and now NextFragment() just calls this new function.
This is needed to implement reactions as OBMols - e.g. if someone wants reagent 1. Also, we really should have it in any case - I've missed it before, and it's not the sort of thing that's simple for the user to throw together. One use case is that it simplifies work with matched pairs, where you are chopping up molecules.
=> Add OBMol::CopySubstructure

src/fingerprints/fingerecfp.cpp, test/testbindings.py
I fixed two problems:
- the fingerprint was being resized to 0 with an initial Clear() so nothing was returned.
- there was an off-by-one when using the atom Idx() to address AtomInfo. This was in the code to handle the nbrs, and lead to an out-of-bounds memory access (with random values sometimes appearing in the fingerprint).
As a general principle, rather than subtracting one from atom indices, we should just use them as provided, and instead increase the size of the referenced data structures by 1. This avoids this sort of error, where you remember to subtract 1 in one place but not another.
=> Get ECFP working

src/mol.cpp, test/testbindings.py
Should have found this earlier...
When deciding whether or not to copy a tet stereo, I neglected to check whether the 'from' atom was copied. As a result, when I later tried to use it, it wasn't there and a segfault occurred.
=> Fix to CopySubstructure found when running over ChEMBL

include/openbabel/forcefield.h, test/testbindings.py
Relocate GetGradientPtr() and GetGradient(atom) for public use, e.g., in Python:
https://gist.github.com/ghutchis/0ecd97aac76b1b3cf99d7113ffb9e376
```
for atom in mol.atoms:
grad = ff.GetGradient(atom.OBAtom)
print(grad.GetX(), grad.GetY(), grad.GetZ(), sep=',')
```
=> Allow public access to retrieve gradients

scripts/openbabel-python.i
Just like you can re-use an OBMol, it would be nice to be able to reuse a std::vector as there might be some performance benefit both from avoiding creating the variable again in Python, and from avoiding some mallocs on the C++ side. With this in mind, I've commented out the SWIG directive to ignore the .clear() method.
=> Re-enable vector.clear() to allow wrapped std::vectors to be reused

src/formats/qchemformat.cpp
Test if an atom has been retrieved before calling SetPartialCharge
+ test if the number of atoms expected by Mulliken paragraph corresponds
to the number of atoms retrieved in the previous Standard Nuclear Orientation paragraph
=> Fix#1331: avoid crash with Q-Chem fragment

src/formats/alchemyformat.cpp, src/formats/balstformat.cpp, src/formats/cacaoformat.cpp, src/formats/chem3dformat.cpp, src/formats/chemdrawct.cpp, src/formats/dmolformat.cpp, src/formats/exyzformat.cpp, src/formats/featformat.cpp, src/formats/fhiaimsformat.cpp, src/formats/freefracformat.cpp, src/formats/gausscubeformat.cpp, src/formats/ghemicalformat.cpp, src/formats/mmodformat.cpp, src/formats/msiformat.cpp, src/formats/opendxformat.cpp, src/formats/pcmodelformat.cpp, src/formats/pdbformat.cpp, src/formats/pdbqtformat.cpp, src/formats/pqrformat.cpp, src/formats/tinkerformat.cpp, src/formats/turbomoleformat.cpp, src/formats/unichemformat.cpp, src/formats/xyzformat.cpp
The same problems of #1569 and #1755 with peek() and tellg() bugs were observed not only in reading molecules in HIN formats, but also in most text-based molecule formats.
This PR modify the blank line cleaning behaviors with the same way of #1755 did.
=>  Modify cleaning blank line behaviors

src/bond.cpp
This is the same as #1724 but for OBBond rather than OBAtom.
=> Ensure that the check for OBBond::IsInRing obeys the OBMol perception flags

include/openbabel/atom.h, include/openbabel/bond.h, src/ring.cpp, test/testbindings.py
Previously, the code that identified ring atoms and bonds did not (un)set the flags of non-ring atoms. This meant that no matter the value of the molecule's ring perception flag, once a ring atom, always a ring atom. The included test case used to fail - it shows that even after deleting an atom from benzene, every atom thinks it's still in a ring.
Part of the problem may have been that there was no way through the public API to reset ring information, so I've had to add the relevant function to OBAtom/OBBond.
=> Ring membership of atoms and bonds was not being reset during perception

src/mol.cpp, test/testbindings.py
This PR has two changes:
1. Keep aromaticity in EndModify()
2. A drive-by removal of code in EndModify() that I recognise as a workaround for the problem fixed in #1724
I know that there's an idea that all lazily perceived flags should be blown away in EndModify(), but I think this is going too far - we should try as far as possible to avoid blowing away information that has been perceived. Here I make a minor change so that aromaticity perception is preserved even when, for example, an atom is deleted (which triggers this code).
IMO, this keeps things simpler and more understandable. Aromaticity will only be reperceived when the user directly unsets the aromaticity flag of the OBMol. Until then, they can delete all they want and nothing will change. If the user deletes an atom from …
=> Keep aromaticity in EndModify()

include/openbabel/atom.h, src/atom.cpp, src/chains.cpp, test/testbabel.py
There are a few related changes here:
1. Move the setting of the HasChainsPerceived() flag into the perception function itself, rather than out here in OBAtom::GetResidue(). What if someone calls the perception function directly? The new behavior is consistent with other perceived properties.
2. Rewrite the function so that it is driven by the HasChainsPerceived() flag, rather than first checking whether the atom has a _residue assigned. This is the behavior I've been fixing for other lazily perceived properties.
3. Remove the code to force (or avoid) perception added by @ghutchis 11 years ago to help Avogadro and others. This looks like a workaround because (2) was not done. How the lazily evaluated system is supposed to work is that you can force or avoid perception using the …
=> Simplify/fix behavior of OBAtom::GetResidue so that it behaves like other lazy properties

src/formats/smilesformat.cpp, test/testbindings.py
Specifying 'f' when writing SMILES allows you to specify the first atom but it also adjusts the H count to facilitate concatenation. I think I'd forgotten this. I've now clarified this in the docstring (also for 'l'), and also added option 'g' that does the same but doesn't adjust the H count.
Note to self: check whether Universal SMILES output is currently using 'f'. If so, it should instead be using 'g'.
=> Updates to SMILES options to specify first and last atoms when writing

src/formats/smilesformat.cpp, test/testbindings.py
Reverts openbabel/openbabel#1870 as it appears to cause a test failure with clang
=> Revert "Updates to SMILES options to specify first and last atoms when writing"

src/formats/adfformat.cpp, src/formats/outformat.cpp
For ADF 2018 (which has not yet been released), the string
"|     D F T B     |" is no longer printed in DFTB output. This
is partially because they changed several of their executables to
run via an "ams" executable instead, including the dftb executable.
Hopefully, "DFTB Engine" will suffice instead... it seems to work thus
far.
=> ADF DFTB: Add new detection string for ADF 2018

src/mcdlutil.cpp, test/testbindings.py
This should fix #1889 
It looks like there was a problem with 0-based and 1-based indexing in mcdlutil.
=> Changed indexing of fragments, should fix #1889

src/formats/smilesformat.cpp, test/testbindings.py
Fixes #1830. Adds support for reading/writing ```[N@@](Br)(Cl)I```, for example.
=> Support lone pair stereo on nitrogen as well as sulfur

src/obiter.cpp
Avoid calling GetBond() when there are no bonds present. Also, reuse numbonds instead of multiple calls to NumBonds(). Fixes #1866.
=> Avoid out-of-range access in OBMolBondBFSIter

src/phmodel.cpp, test/regressionstest.cpp
Fix OBChemTsfm handling where the implicit H count was going below 0 and wrapping. As reported by @bbucior. See #1895 for more info. Includes the test case reported by Ben along with another one for the same problem triggered by bond order changes.
=> Fix OBChemTsfm wrapping of implicit H counts

src/mol.cpp
Fixes https://github.com/openbabel/openbabel/issues/1907
=> Fix incorrect use of `memcpy`.

data/gaff.dat, src/chiral.cpp, src/distgeom.cpp, src/elementtable.h, src/formats/MCDLformat.cpp, src/formats/MNAformat.cpp, src/formats/mpdformat.cpp
Hello :-)
The DOI foundation recommends [this new resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Yes, a bit ironic that they would change the URL of their service, but it's now [encrypted](https://www.ssllabs.com/ssltest/analyze.html?d=doi.org). Because the old links with the `dx` subdomain continue to work, there is no urgent need to do anything.
However, I'd hereby like to suggest to follow the new recommendation by applying this update to all static DOI links.
Cheers!
=> Hyperlink DOIs to preferred resolver

src/formats/smilesformat.cpp
Minor fix. Clang rightly warns about my setting ```int _rxnrole = 1;``` in the variable declaration of SmilesParser:
```
in-class initialization of non-static data member is a C++11 extension
[-Wc++11-extensions]
```
=> Fix clang warning about in-class init of a non-static data member

CMakeLists.txt, test/CMakeLists.txt, test/testbabel.py
Newer CMakes warn that CMake policies CMP0005 and CMP0042 are being set to OLD. This PR addresses CMP0005 by removing the problematic definition - as far as I can tell, it's unneeded - in fact, it wasn't being handled correctly and once it was, it caused warnings due to duplicate definition in babelconfig.h.
The other policy warning is discussed a bit in https://github.com/openbabel/openbabel/pull/85.
=> Address CMake build warning about policy CMP0005 being set to OLD

include/openbabel/mol.h, src/forcefield.cpp, src/forcefields/forcefieldgaff.cpp, src/formats/mdlformat.cpp, src/formats/smilesformat.cpp, src/mol.cpp, src/tautomer.cpp, test/testbindings.py
(Part of the pre-3.0 API cleanup)
The current situation is that some molecular perception flags have an unset method. Others do not. Furthermore, some setters take a boolean for set/unset (full disclosure - this may have been all me).
The latter approach of a single method with a boolean seems reasonable. It reduces the number of methods, reduces the developer error (forgetting to add an unset method), and frankly is easier for users - just one method to do two things. 
This PR gets rid of the Unset methods for molecule flag perception, and ensures that all setters (for perception flags) take a boolean. I've also moved HasFlag and SetFlag from "protected" to "public". I get the idea of encapsulation, but consider the case where the user wants to set a custom flag. I can move it back if …
=> Tidy setting/unsetting of molecule perception flags

.travis.yml
When a test fails, it would be nice to see the test output, especially for those cases where I'm having trouble reproducing the test failure.
=> For Travis builds, include output for build failures

scripts/openbabel-R.i, scripts/openbabel-csharp.i, scripts/openbabel-java.i, scripts/openbabel-mono.i, scripts/openbabel-perl.i, scripts/openbabel-php.i, scripts/openbabel-ruby.i
I had updated the Python bindings to take account of #1958, but not the others. This should fix #1962 hopefully.
=> Update bindings for changes to headers

test/testbindings.py
The gradient test was failing randomly as calling GetGradient() appears to just return random numbers (different values each time). This fixes it by ensuring that Energy() is called first. This may be a problem in the underlying C++, but for now, this sorts it out.
=> Fix randomly failing Python gradient test

include/openbabel/generic.h
This convenience function should never have been added (https://github.com/openbabel/openbabel/pull/17) to what is a core classes of the toolkit. Fixes #1913 by removing the offending function.
=> Remove GetGenericValueDef from OBGenericData

include/openbabel/conformersearch.h, include/openbabel/math/matrix3x3.h, include/openbabel/math/vector3.h, include/openbabel/obutil.h, scripts/openbabel-R.i, scripts/openbabel-csharp.i, scripts/openbabel-java.i, scripts/openbabel-mono.i, scripts/openbabel-perl.i, scripts/openbabel-php.i, scripts/openbabel-python.i, scripts/openbabel-ruby.i, src/conformersearch.cpp, src/distgeom.cpp, src/forcefield.cpp, src/formats/smilesformat.cpp, src/math/matrix3x3.cpp, src/math/vector3.cpp, src/rand.cpp, src/rand.h, test/math.cpp, tools/obconformer.cpp, tools/obrotamer.cpp
(Proposed PR as part of the API cleanup)
This removes OBRandom from the public API. It's still there, and included via # include. The changes are a bit hacky for the moment, but removing it gives us some breathing space to fix problems and bring it back (if that's what makes sense). 
So OBRandom will probably come back at some point, but it won't be the same. This code of Roger's is not a general pseudorandom number generator, but an iterator over a fixed (and small) set of intergers in pseudorandom order. The details are actually in a talk that's online from when Roger was in Metaphorics (insert reference in here from future).
This is part of the problem. The other part is that random numbers are being used with a time seed throughout the codebase in a way that hampers reproducibility. …
=> Remove OBRandom from the public API

include/openbabel/atom.h, include/openbabel/bitvec.h, include/openbabel/mol.h, include/openbabel/ring.h, include/openbabel/rotor.h, src/atom.cpp, src/forcefield.cpp, src/forcefields/forcefieldgaff.cpp, src/forcefields/forcefieldghemical.cpp, src/forcefields/forcefieldmmff94.cpp, src/forcefields/forcefielduff.cpp, src/formats/smilesformat.cpp, src/graphsym.cpp, src/kekulize.cpp, src/mol.cpp, src/residue.cpp, src/ring.cpp, src/rotamer.cpp, src/rotor.cpp, src/stereo/perception.cpp
I've removed some deprecated methods (found by grepping *.h for "deprecated"). Some of these are renamed methods, where the old name was deprecated but never removed. Others are not recommended for use e.g. NewAtom.
There are a whole bunch of deprecated methods in forcefield.h, grid.h and rotor.h. I don't think I'm going to dig into these right now, as I don't know the background, but @ghutchis you might want to.
=> Remove low-hanging deprecated methods

.gitignore
The `scripts/python/openbabel/__init__.py.in` file was added in #1946, generating file `scripts/python/openbabel/__init__.py`. The generated file should be added into gitignore.
=> Add __init__.py to gitignore

include/openbabel/atom.h, include/openbabel/bond.h, src/depict/depict.cpp, src/forcefields/forcefieldmmff94.cpp, src/formats/mol2format.cpp, src/formats/smilesformat.cpp, src/typer.cpp, tools/obrms.cpp
Similar to #1951 which was for OBMol perception flags, this tidies up the Set/Unsetters into a single function ``SetXXXX(bool value=true)`` for OBBond and OBAtom.
=> Move to a single function for setting/unsetting bond and atom flags

scripts/CMakeLists.txt
See https://bugs.launchpad.net/ubuntu/+source/python3-defaults/+bug/1814653
Fix might be slightly fragile - not sure if it would be better to check
for Ubuntu 18.04 directly
=> Address Ubuntu bug in defining python install dir

src/formats/smilesformat.cpp, test/testbindings.py
The original patch is from @rogersayle, which I've restricted a bit. This is is a SMILES extension that is already present in OEChem and RDKit, both undocumented and due to Roger. For at least OEChem, support is present for 1- and 2-digit numbers too.
The primary use case is to support new elements where we don't yet have the symbol, but also to read SMILES written by OEChem/RDKit where *they* don't yet have the symbol.
My own take is that this seems relatively safe, at least if restricted to 3-digits. As an implementation detail, if an atomic number >255 is specified, the SMILES is rejected with a warning (we use a char for the atomic number).
=> Add SMILES support for elements specified by 3-digit number, e.g. [#101]

include/openbabel/math/vector3.h
vector3.h includes no other openbabel headers and so OBAPI is not defined.  This is a not a problem with user code - it is reasonable to expect a library's header files to be syntactically correct regardless of what order they are included.
=> include babelconfig in vector3.h 

scripts/python/openbabel/pybel.py
I have made some change of `pybel.py` to compatible with function name changes in #1975. Some property names were changed keeping the original name as the alias.
`heavyvalence` -> `heavydegree`
`heterovalence` -> `heterodegree`
=> Make pybel compatible with #1975

include/openbabel/builder.h, src/builder.cpp, src/mol.cpp, test/addhtest.cpp
This is an alternative fix to generating crazy hydrogens.  Instead of defaulting to a hybridization 2 kind of bond, if the builder doesn't think there is a reasonable bond vector, then the hydrogen isn't added.  I've also updated the documentation for GetNewBondVector to state that a non-finite vector can be returned if there isn't a reasonable location for another atom.
This restores the old behavior of GetNewBondVector (return non-finite bond vectors), which is good in the off chance anyone was relying on it while still fixing the problem.  In the corner case that a molecule has multiple conformers, some where the hydrogen can be added and some where it can't the hydrogen is added at (0,0,0), but I'm not sure this can actually happen.
This also comes with updated hydrogen testing code. …
=> H vector fix

src/ops/gen3d.cpp
When 3D coordinates were generated with obabel, `fast` and `fastest` options yielded the same structure. This is because `UpdateCoordinates()` was missing after force field cleanup when ` fast` is specified. This pull request solves this issue.
=> Update coordinates in the fast option of obabel

src/transform.cpp
When both of `-p` and `-h` options are set, the `obabel` will behave as adding all implicit atoms without considering the pH environment, just like using `-h` only.
This PR adds a warning message to warn users when both of these options are set.
=> Add a warning message when both -p and -h options are set

src/formats/smilesformat.cpp
The original description of the SMILES 'k' option, which is new in this release, caused the GUI to turn it on by default. That was not intended.
=> Don't make kekule SMILES the default in the GUI [skip ci]

src/kekulize.cpp
Valgrind was reporting Conditional jump or move depends on uninitialised value(s)
I am pretty sure that initializing to zeroes is the right thing to do,
but don't really grok the kekulize code so perhaps this is a symptom of
a larger problem.  It's certainly an improvement over reading
uninitialized values.
=> Fix reading of uninitialized data.

.github/FUNDING.yml
This is used to enable open financial contributions
(e.g., meetings at ACS, etc.)
https://opencollective.com/openbabel
=> Add a GitHub funding link to the open collective page.

CMakeLists.txt, INSTALL
`CMAKE_CXX_STANDARD` is currently used
https://github.com/openbabel/openbabel/blob/41730e2d82d01eb52cc5a58ed60000c533ee8ce9/CMakeLists.txt#L474
But it was introduced in [CMake 3.1](https://cmake.org/cmake/help/v3.1/release/3.1.0.html#properties).
=> Bump cmake_minimum_required to 3.1

include/openbabel/forcefield.h, src/forcefield.cpp
The variable was called as Boltzmann's constant but actually gas constant, and the value was incorrect.
=> Update GAS CONSTANT to 2018 CODATA recommended value

scripts/CMakeLists.txt
The R bindings prevented many script bindings from building.
Make sure to generate the DLL in the source directory for C# (i.e., for distribution)
=> Fix CMake error with R and C# bindings

src/formats/maeformat.cpp
The file extensions should be lowercase for .mae and .maegz. See discussion at #1993.
=> Rename MAESTRO extensions from uppercase to lowercase

CMakeLists.txt, openbabel-3.pc.cmake
pkgconf file still points to `include/openbabel-2.0`; use `BABEL_MAJ_VER` for convenience.
=> Do not hard-code Open Babel major version for include directory

CMakeLists.txt
maeparser doesn't appear to support static builds out of the box, so
disable it in this case
=> Fix BUILD_SHARED=OFF

INSTALL, OpenBabel3Config.cmake.in, OpenBabel3ConfigVersion.cmake.in, doc/examples/static_executable/CMakeLists.txt, doc/obabel.1, doc/obchiral.1, doc/obconformer.1, doc/obdistgen.1, doc/obenergy.1, doc/obfit.1, doc/obgen.1, doc/obgrep.1, doc/obgui.1, doc/obminimize.1, doc/obprobe.1, doc/obprop.1, doc/obrms.1, doc/obrotamer.1, doc/obrotate.1, doc/obspectrophore.1, doc/obsym.1, doc/obtautomer.1, doc/obthermo.1, doc/roundtrip.1, scripts/java/README, scripts/perl/META.yml, scripts/perl/README, scripts/python/README.rst, scripts/python/setup.py, src/doxygen_pages.cpp
- Update INSTALL and READMEs under scripts/
- perl
- assume perl-binding version is different from Open Babel's
- python
- assume tarball from github release page
- note: `python scripts/python/setup.py install` does not work since `__init__.py` is missing
- Update version and release date of man
- Update variables in CMake files to version 3
- Update scripts/python/setup.py
=> Update for Open Babel 3

CMakeLists.txt
When working on the Windows conda-forge versions, I got a compile error on the maeparser code (https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=90306&view=logs&jobId=171a126d-c574-5c8c-1269-ff3b989e923d&taskId=7225e372-3a5e-5b11-c153-719d50bbeacd&lineStart=510&lineEnd=528&colStart=1&colEnd=1) due to a mismatch between the calls to find_package in OpenBabel and Maeparser. In OB, there was a check for plain Boost to decide if Maeparser should be built but in the building of Maeparser, there were some component required. This PR will check for those components also in the OB code. That way, if the required components are missing, OB will just drop mae support instead of failing to compile.
There are still several checks for Boost libraries in CmakeLists.txt, leading …
=> Fix maeparser compile error with some Boost configs

src/parsmart.cpp, test/testbindings.py
The SMARTS parser did not support #0 to indicate an asterisk. This PR adds support...by removing two lines from the source code. :-)
=> Support #0 in SMARTS so that asterisks can be matched

.travis.yml, CMakeLists.txt, cmake/modules/Findcoordgen.cmake, cmake/modules/Findmaeparser.cmake, src/CMakeLists.txt, src/formats/maeformat.cpp
This is meant as an improvement: with these changes, CMake first checks if there is a build of Schrödinger's maeparser and coordgen libraries that can be used in openbabel's build. If there isn't, then, this patch downloads the sources and builds them.
This means that it addresses #2015.
Some notes:
- CMake will, by default, look in standard library and include directories for the built library and the required headers. Other directories can be specified for the lookup by using "maeparser_DIR" and "coordgen_DIR".
- By default, the "master" branch of maeparser and coordgen will be downloaded from GitHub. This can be changed using the "MAEPARSER_VERSION" and "COORDGEN_VERSION" variables, pointing them to specific tags, branches or commits.
- If sources are already present at the directory …
=> Find or build maeparser & coordgen libraries

doc/CMakeLists.txt, src/conformersearch.cpp, src/formats/confabreport.cpp
=> patched to build on NetBSD

include/openbabel/mol.h
Change the docstrings of add/delete hydrogens to refer to explicit<->implicit rather than adding or deleting hydrogens (because that's not what they do).
=> Change docstrings of add/delete hydrogens

src/CMakeLists.txt, src/ops/neutralize.cpp, test/testbindings.py
Together with the ``-r`` option for "strip all but the largest component", neutralize is often an essential first step for standardising a dataset of molecules (especially as provided by vendors).
Here's the help text from ```obabel -L neutralize``` (some additional background at https://baoilleach.blogspot.com/2019/12/no-charge-simple-approach-to.html):
```
One of the ops
neutralize    Neutralize +1 and -1 charges
Note: this method accepts an optional argument 'changed' which is
described below.
This method uses a simple procedure to generate the neutral form of a
molecule. It does not attempt to balance charges but simply to convert
all atoms with a +1 or -1 charge to neutral by addition or subtraction
of H+.
To a first approximation the procedure is simply to identify all atoms with …
```
=> Add the --neutralize operation to convert charged atoms to neutral

scripts/CMakeLists.txt
This hopefully fixes #2081 so that the Python bindings can be built directly from the source release (i.e. without SWIG).
=> Correct the path to the openbabel-python.cpp

src/kekulize.cpp, test/testbindings.py
Previously ```O=s1(=O)cccn1``` caused a kekulization failure. Now it's read as ```O=S1(=O)C=CC=N1```.
=> Support kekulization of aromatic sulfoxides

CMakeLists.txt
Fix #2089.
See https://github.com/schrodinger/maeparser/blob/v1.2.3/CMakeLists.txt#L8
for the option.
maeparser will be build if Boost_FOUND.
=> Set MAEPARSER_BUILD_SHARED_LIBS (fix #2089)

src/formats/smilesformat.cpp, test/testbindings.py
Previously the following were parsed (copied and pasted from the tests) - now they are rejected as invalid:
```
"[CH2++2]",
"[C+-+-]",
"[C+2+]"
"[CH2--2]",
"[C-+-+]",
"[C-2-]"
```
=> Be more strict when parsing charges in SMILES

scripts/python/openbabel/pybel.py, scripts/python/setup.py
While following the example at https://open-babel.readthedocs.io/en/latest/UseTheLibrary/PythonInstall.html#test-the-installation, noticed that the `mol.draw()` step fails on importing of `Tkinter` in Python 3.7. The module was renamed to `tkinter` in Python 3+ versions, and the `six` library supports the proper handling of the change: https://six.readthedocs.io/#module-six.moves (thanks to @tacaswell for the reference). I added `six` as the install requirement.
=> Fix the import of Tkinter in Python 3+

src/formats/mol2format.cpp, test/files/5sun_protein.mol2, test/testbabel.py
Generally speaking, it is better to check if a pointer is NULL _before_
dereferencing it rather than after.
=> Fix for segault (with regression test)

doc/obconformer.1, doc/obconformer.html, tools/obconformer.cpp
* Enable to accept forcefield (default: MMFF94)
* remove unused variables
* clang-format
=> Improve tools/obconformer.cpp

.github/workflows/build_cmake.yml, src/builder.cpp, test/testdistgeom.py
Thanks to Cristian Adam for a template (and blog article)
https://cristianadam.eu/20191222/using-github-actions-with-c-plus-plus-and-cmake/
https://raw.githubusercontent.com/cristianadam/HelloWorld/master/.github/workflows/build_cmake.yml
=> Initial CMake GitHub Action

src/ops/forcefield.cpp
There are sometimes needs (e.g. in my research) to minimize
with unusual structures - allow minimize without adding H
=> Allow minimizing without adding hydrogens - not the default

scripts/openbabel-java.i
Workaround a problem in SWIG 4.0.1 (at least) where the generated Java source relies on reserve being present. See https://github.com/swig/swig/issues/1787.
=> Workaround for SWIG 4.0.1 Java source code problem

.github/workflows/build_bindings.yml
This will be a separate build script because eventually this
will generate the *source* with all bindings updated, not a binary
(e.g. to automate releases)
=> Add a build for bindings (eventually will generate source tar)

test/addhtest.cpp
This include is required for `alloca()`.
Reference: <https://illumos.org/man/3c/alloca>
=> Fix build on illumos

include/openbabel/atom.h, include/openbabel/bond.h, include/openbabel/chains.h, include/openbabel/data.h, include/openbabel/graphsym.h, include/openbabel/internalcoord.h, include/openbabel/mol.h, include/openbabel/plugin.h, include/openbabel/residue.h, include/openbabel/typer.h, src/atom.cpp, src/config.h.cmake
Discovered with Ruby 2.5 SWIG bindings
=> Rename EXTERN to OB_EXTERN to prevent clashes in other headers

include/openbabel/tautomer.h, src/tautomer.cpp, test/CMakeLists.txt, test/tautomertest.cpp, tools/obtautomer.cpp
Various improvements and fixes for the tautomer code.
- Fix issue #227 
- Fix various backtracking issues (rewritten using RAII)
- Perceive aromaticity for each tautomer (fixes failing antralin test)
- Mark atoms that have initially have all bonds assigned as Other (fixes failing tenoxicam test which contains sulfon group)
- Add support for enumerating unique tautomers only (duplicates may be present due to symmetry)
- Add test cases from slides, all are working now (see https://www.daylight.com/meetings/emug99/Delany/taut_html/sld030.htm)
TODO:
- More testing with special functional groups (e.g., N-oxide, conjugated carbanion/carbocation, conjugated nitrogen)
- Add support for keto/enol tautomerism?
=> Fix tautomer code

src/CMakeLists.txt, src/doxygen_pages.cpp
This in response to #2197
Don't include a dependencies on libboost_system in libopenbabel .  Separate code for pulling in threads from boost check.
I've also fixed the case of the cmake documentation (OpenBabel3 instead of OPENBABEL3).  
I have questions though:
- OpenBabel3_INCLUDE_DIR or OpenBabel3_INCLUDE_DIRS?  There is a mismatch between documentation and code
- Does cmake automatically define OpenBabel3_FOUND?  I don't see where we define it in OpenBabel3Config.cmake.in
- Should the documentation no long describe FindOpenBabel3.cmake since we have the cmake.in file to be installed in the standard place?
=> CMake: separate thread import from boost

src/mol.cpp
```
[92/558] Building CXX object src/CMakeFiles/openbabel.dir/mol.cpp.o
In member function ‘void OpenBabel::OBMol::ConnectTheDots()’:
cc1plus: warning: ‘void* __builtin_memset(void*, int, long unsigned int)’: specified size 18446744073709551608 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
```
The change I've made is to guard against a negative value. I think the compiler is maybe being extra cautious. On the other hand, maybe it's a true logic error in the original code - can you take a quick look @ghutchis.
=> Fix the compiler warning about large object size

include/openbabel/conformersearch.h, src/conformersearch.cpp, src/ops/conformer.cpp
Instead callers must release objects.
Fix #2066, fix #2221.
=> Do not release OpenBabel::OBConformerSearch::m_score

src/fingerprints/finger3.cpp, src/formats/yasaraformat.cpp
Fixes three miscellaneous undefined behaviors:
1. One instance of using memcpy() with overlapping source and
destination strings.
2. One instance of reading and modifying an object without an
intervening sequence point.
3. One modification of an object via a pointer to a different,
unrelated type.
=> Fixes miscellaneous undefined behaviors

src/forcefields/forcefielduff.cpp
When evaluating atom coordination number, method
OBForceFieldUFF::ParseParamFile() assumed that it may access a third character
of the atom type string, but in fact that produces undefined behavior if the
string is only one character long. A one-character atom type occurs in
practice with the default parameter file (for deuterium).
This change addresses the issue by verifying that the second character of
each atom type string is not a C string terminator as a precondition for
accessing the third. If the second is a string terminator then the same
default behavior is provided as if the type were two characters long.
Fixes #2223
=> Fix UB in UFF parameter parsing

test/testdistgeom.py
When run with Python 3.6, test/testdistgeom.py fails with a SyntaxError
about a malformed character escape.  This arises from a failure to escape
literal backslash characters in single-quoted SMILES strings (several
occurrences).  Python 2 accepts this and does the right things with it,
but Python 3 rejects it.
Fixes #2217
=> Fix test failure with Python 3

src/math/spacegroup.cpp, test/cifspacegrouptest.cpp
Tested with valgrind, see https://github.com/openbabel/openbabel/pull/2220.
=> Fix memory leaks in spacegroup.cpp and cifspacegrouptest.cpp

src/mol.cpp
After this fix, valgrind reports no leaks ([valgrind-out.txt](https://github.com/openbabel/openbabel/files/4631753/valgrind-out.txt)) when running mol test (besides the dlopen ([supr.txt](https://github.com/openbabel/openbabel/files/4631752/supr.txt))):
```
valgrind --leak-check=full  --show-leak-kinds=all --track-origins=yes --log-file=valgrind-out.txt --suppressions=../supr.txt ./bin/test_runner mol 1
```
=> Fix memory leak in mol.cpp

src/mcdlutil.cpp
Fixes three instances of catching polymorphic exceptions by value
instead of by reference.
=> Fixes catching polymorphic exceptions by value

doc/examples/obconformersearch_default.cpp
The example program obconformersearch_default does not build
successfully with GCC 8.3.1 and its accompanying C++ standard
library.  The issue revolves around its use of a non-namespaced
shared_ptr template.  Since the source already includes the header
needed to use OB's shared pointer alias, obsharedptr, this
commit resolves the issue by making it use that alias (as opposed to
by using std::shared_ptr explicitly).
=> Fix examples failing to build with GCC / libstdc++ v8.3

scripts/python/setup.py
``setup.py`` is used for pip installs on Linux. python 2.7 is the default Linux on Ubuntu 18.04 (for example), which has long-term support until 2023.
=> Support Python 2.7 in setup.py

src/formats/smilesformat.cpp, test/testbindings.py
Ensure that specifying the output atom order in SMILES does not cause any hydrogens to be suppressed. This occurred if the atom written first was a bracket atom with a hydrogen count:
```
$ obabel  -:"c1[nH]ccc1" -osmi -xo "2-3-4-5-1"
[n]1cccc1
```
=> Fix hydrogen suppression when specifying SMILES atom order

src/formats/gaussformat.cpp, tools/obthermo.cpp
The pointgroup code has been disabled in obthermo because a
crash  was introduced relating to the link between OBatom and
OBmol.
=> Fixed crash in obthermo due to pointgroup code.

src/obiter.cpp, test/iterators.cpp
The constructor was not initializing _ptr to null, and this is what was
used to test the validity of the iterator.  This caused iteration over a
ringless molecule (e.g. empty) to sometimes fail (segfault or infinite
loop).  But not always.
=> Fix ring iterations w/no rings

.github/workflows/build_cmake.yml, .github/workflows/misspell-fixer.yml
For the GitHub workflows, the `set-env` and `set-path` commands have been deprecated and removed.
- https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
- https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16/
This PR replaces one `set_env` command in the `build_cmake.yml` according to the GitHub Environment Files documentation.
- https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#environment-files
Also, the `peter-evans/create-pull-request` has also been updated to 3.8.0 as well for this issue.
=> Replacing deprecated set-env and set-path commands

scripts/python/openbabel/pybel.py, test/testbindings.py
Some properties (e.g. implicitvalence) are no longer available.
Also added index as a property and a test.
=> Fix missing atom pybel properties.

cmake/modules/Findcoordgen.cmake
The coordgen upstream does not install the template file. It is
also not required at runtime, since its contents are compiled into
the coordgen library itself.
Fixes #2214
=> Do not search for coordgen template files

include/openbabel/typer.h, src/formats/MCDLformat.cpp, src/formats/xtcformat.cpp, src/kekulize.cpp, src/mcdlutil.cpp, tools/obrms.cpp
It is arguable if this is strictly better (you won't see uninitialized
reads in valgrind when debugging memory errors) but seems like good
defensive programming to me.  I don't know of any bugs that are fixed as
a result of not having uninitialized memory, but this was motivated by
another bug involving uninitializd memory and the changes have been
sitting in my fork for a while.
=> Initialize allocated memory to zero.

src/formats/copyformat.cpp, src/formats/fastsearchformat.cpp, src/formats/fingerprintformat.cpp, src/formats/getinchi.cpp, src/formats/pngformat.cpp, src/formats/svgformat.cpp, src/formats/textformat.cpp
Some format descriptions still use the obsolete command `babel` in their example or other parts. This PR updates the descriptions and comments of 7 formats: `copy`, `fs`, `fpt`, `inchi`, `png`, `svg`, and `text`.
=> Update descriptions of formats

test/CMakeLists.txt, test/fuzz/fuzz_obconversion.cpp
cc @ghutchis as discussed in https://github.com/google/oss-fuzz/pull/5492#issuecomment-806180790
The smiles fuzzer quickly finds a buffer overread
The sdf fuzzer quickly finds a memory leak
=> First fuzz targets for integration with oss-fuzz

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Now GitHub can offer multiple issue templates.
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
=> Separate issue templates [skip ci]

src/phmodel.cpp, test/testbabel.py
This is a bug report from Stefano Forli on the openbabel-devel list.
When calling obabel with -p the pH model infers formal charges on an xyz
(since the format doesn't support them) but the code was always
incrementing the number of hydrogens if a charge is added, even if there
were already the appropriate number of explicit hydrogens.  Change the
code to call OBAtomAssignTypicalImplicitHydrogens after updating the
formal charge.  Include a regression test.
=> Fix for ammonium xyz parsing.

src/confsearch.cpp
make stdout writes dependent on verbose flag that allow to turn off logs completely
=> verbose flag in OBForceField for all stdout writes

src/formats/gaussformat.cpp
**When merged this pull request will:**
- Prevent parser from matching ` Dipole orientation:` if no input orientation was printed.
- `obabel H2O_freq.log -O H2O.cml` work with [H2O_freq.log](https://github.com/openbabel/openbabel/files/8307662/H2O_freq.log)
=> Fix search of coordinate system

.github/workflows/build_bindings.yml
```
tar: The following options were used after any non-optional arguments in archive create or update mode.  These options are positional and affect only arguments that follow them.  Please, rearrange them properly.
tar: --exclude-vcs has no effect
tar: --exclude-backups has no effect
tar: --exclude ‘.github*’ has no effect
tar: Exiting with failure status due to previous errors
```
=> ci: rearrange tar options properly

src/formats/pdbformat.cpp
Not all istream implementations support tell/seek so use peek when
consuming blank lines.
=> More robust pdb reading.

.github/workflows/lint_python.yml, test/testobconv_writers.py
Results: https://github.com/cclauss/openbabel/actions
https://flake8.pycqa.org/en/latest/user/error-codes.html
On the flake8 test selection, this PR does  _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead, these tests focus on runtime safety and correctness:
* __E9__ tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic language like Python, they result in the script halting/crashing on the user.
* __F63__ tests are usually about the confusion between identity and …
=> GitHub Action to lint Python code

src/formats/tinkerformat.cpp
Previously, tinkerformat.cpp assumed that the first line contained **both** the number of atoms and a comment/title. In cases where it only contained the number of atoms, reading the file would fail.
This also contains improvements that clean up and use more built-in functions/macros.
Fixes #2321
=> Clean up Tinker formatting and allow for no comment

scripts/CMakeLists.txt
This change will build _openbabel.so in scripts/python/openbabel instead
of the default build/lib.  This is necessary because openbabel.py tries
to import _openbabel like this:
if __package__ or "." in __name__:
from . import _openbabel
else:
import _openbabel
This results in a circular import error when running make test (the
first branch of the if is triggered).  This code appears to be generated by
SWIG with no obvious way to change it to catch the ImportError and call
import _openbabel instead.  Note the PYTHONPATH is set to include
build/lib, but it doesn't matter because SWIG is forcing the import to
happen in scripts/python/openbabel.
I'm not sure why this hasn't been a problem in the past, perhaps there's
been a change in SWIG.  This is with SWIG 4.0.1 and cmake 3.18.6.
I think …
=> Resolve ImportError with make test

src/formats/fastaformat.cpp
Should fix #2367
I'm not that used to the difference between mol->AddBond vs mol->NewBond so there might be some side effects, but this change seems to work.
=> Make FASTA conversion really connect the atoms.

scripts/CMakeLists.txt
* `-DPYTHON_INSTDIR=...`
* `-DJAVA_INSTDIR=...`
* `-DR_INSTDIR=...`
* `-DPERL_INSTDIR=...`
* `-DRUBY_INSTDIR=...`
* `-DCSHARP_INSTDIR=...`
* `-DPHP_INSTDIR=...`
*  `-DPYTHON_INSTDIR=...` shall override `PYTHON_INSTDIR` in `scripts/CMakeLists.txt`
* We can designate install dirs for language bindings through the options above, while keeping default install dirs of language bindings except python are `LIB_INSTALL_DIR`.
This PR does not break current configurations.
=> Make install-dir configurable for each binding

src/depict/depict.cpp, src/distgeom.cpp, src/forcefield.cpp, src/formats/mol2format.cpp, src/formats/mopacformat.cpp, src/mcdlutil.cpp, src/obconversion.cpp, src/oberror.cpp, src/parsmart.cpp
`delete nullptr;` has no effect and there is no necessity to check if a pointer is not `nullptr`.
=> clang-tidy: readability-delete-null-pointer

include/openbabel/conformersearch.h, src/conformersearch.cpp, src/ops/conformer.cpp
related to https://github.com/openbabel/openbabel/pull/2229, current implementation causes segmentation fault after call SetFilter from python
=> Do not release OpenBabel::OBConformerSearch::m_filter

src/formats/gamessukformat.cpp, src/formats/orcaformat.cpp
<regex> has been in C++11 std, so it may be used directly,and it can be compiled with msys2 successfully.
=> Used <regex> directly

src/config.h.cmake
Without this fixed check, we get a build failure with GCC 12:
```
/var/tmp/portage/sci-chemistry/openbabel-3.1.1_p20210225/work/openbabel-08e23f39b0cc39b4eebd937a5a2ffc1a7bac3e1b/include/openbabel/obutil.h:65:14: error: ‘clock’ was not declared in this scope; did you mean ‘clock_t’?
65 |       start= clock();
|              ^~~~~
|              clock_t
```
Bug: https://bugs.gentoo.org/851510
=> CMake: fix time check typo (fixes build failure w/ GCC 12)

include/openbabel/obmolecformat.h, src/obmolecformat.cpp, src/ops/unique.cpp
The checks are no longer necessary as C++11 is now used.
=> refactor: use `std::unordered_map` for hash map

include/openbabel/atom.h, include/openbabel/bond.h, include/openbabel/data.h, include/openbabel/forcefield.h, include/openbabel/grid.h, include/openbabel/griddata.h, include/openbabel/math/matrix3x3.h, include/openbabel/math/vector3.h, include/openbabel/mol.h, include/openbabel/obutil.h, include/openbabel/parsmart.h, include/openbabel/patty.h, include/openbabel/ring.h, include/openbabel/rotor.h, src/atom.cpp, src/config.h.cmake, src/data.cpp, src/math/matrix3x3.cpp, src/math/vector3.cpp, src/obutil.cpp
Define `OB_DEPRECATED` and `OB_DEPRECATED_MSG` to declare classes, functions, and variables are deprecated.
Unless `[[deprecated]]` attribute is effective (C++14 feature) or `SWIG` is defined, these macros are ignored
=> Add deprecated attribute

include/openbabel/inchiformat.h, include/openbabel/plugin.h, scripts/openbabel-R.i, scripts/openbabel-csharp.i, scripts/openbabel-java.i, scripts/openbabel-perl.i, scripts/openbabel-php.i, scripts/openbabel-python.i, scripts/openbabel-ruby.i, src/ops/sort.cpp
=> Remove std::binary_function, which is removed in C++17

src/formats/povrayformat.cpp, src/stereo/perception.cpp
`std::bind1st` is deprecated in C++11 and removed in C++17.
=> Remove deprecated std::bind1st

scripts/python/examples/testpybel.py, scripts/python/openbabel/pybel.py
There are two minor issues in Python interface `pybel` module `readfile` function:
It has arguments like `readfile(format, filename, opt=None)`, argument `format` is mandatory required, however, it should have the ability to be guessed from the input `filename`, which is also required. Secondly, for `openbabel`, the compressed `gzip` filetype can also be supported in some extents. User may feel confused with which type of “correct” file format should be input if they happen to have a `gzip` file like “**file.sdf.tgz**" or the equivalent things.
To be noted: in order to be maximumly compatible with early version of `pybel`, the sequence of arguments inside are kept consistent.
With the new version of codes, `readfile` can be used to read file like: `readfile(filename=”head.sdf.tgz”)`.
=> update interface pybel.py

src/formats/json/pubchemjsonformat.cpp
In current master, when converting to pubchem json, x coordinates are always identical to y coordinates. This PR fixes that bug.
=> Fix bug in pubchem json coordinate writing

src/distgeom.cpp
This bug was discovered while testing out the new iterators. The old iterator marcos used iterators that had an operator bool() which implicitly converts into unsigned long. Instead of using the atom's id, a boolean value was used for IsCis/IsTrans.
=> Fix bug in distance geometry code

src/formats/groformat.cpp
* when the first resid is 0, it will trigger object res without initialization
* fix bug by checking whether object res is nullptr
=> fix bug when read gro file as first residue idx is 0

src/formats/xml/cmlformat.cpp, test/CMakeLists.txt, test/regressionstest.cpp
=> Proper aromatic support for CML

src/formats/xml/xml.cpp
This PR fixes the single incompatibility with libxml 2.12.7 which [has been reported on Debian package](https://bugs.debian.org/1073327). Please note this PR does not update the libxml sources as included under `include/libxml/`.
=> Restore compatibility with libxml 2.12.7

CMakeLists.txt
Version 1.1.0 of rapidjson is now 8 years old, and building Open Babel is currently broken on recent Linux systems as a result. Using the current code incorporates the many patches since 2016 such as [this PR](https://github.com/Tencent/rapidjson/pull/719).
=> Fetch more recent rapidjson codebase rather than last release

src/data.cpp, src/formats/MCDLformat.cpp, src/formats/abinitformat.cpp, src/formats/adfformat.cpp, src/formats/gulpformat.cpp, src/formats/xsfformat.cpp, test/CMakeLists.txt, test/fuzz/fuzz_convert.cpp
A new fuzzer is implemented - fuzz_convert. It tests `OBConversion::Convert` function will randomized input/output formats and data. It will help to find many crashes - some of them I will report one by one later, but we already can merge this PR to increase coverage. Additional changes in this PR:
1. src/data.cpp: oot of bound read in `OBGlobalDataBase::Init()`
2. src/formats/MCDLformat.cpp: usage of uninitialized variable `numdups` that leads to OOM or crashes
3. src/formats/adfformat.cpp: fix infinite loop in case of unexpected end of input
4. src/formats/abinitformat.cpp: prevent division by zero
5. src/formats/gulpformat.cpp: fix infinite loop in case of unexpected end of input
6. src/formats/xsfformat.cpp: prevent division by zero
=> Implement fuzz_convert fuzzer

src/formats/inchiformat.cpp
This fixes a crash when an invalid InChI is provided. For example: `InChI=1S/H2O_h1H2`
=> Don't crash on an invalid InChI

src/formats/xml/cmlformat.cpp
Fixes crash which happens for this structure:
```xml
<molecule molID="m1">
<atomArray atomID="a1 a2 a3 a4 a5 a6" elementType="C O C O C O" />
<bondArray>
<bond id="b1" atomRefs2="a1 a2" order="2">
<bondStereo>C</bondStereo>
</bond>
<bond id="b2" atomRefs2="a2 a3" order="1" />
<bond id="b3" atomRefs2="a3 a4" order="2">
<bondStereo>C</bondStereo>
</bond>
<bond id="b4" atomRefs2="a4 a5" order="1" />
<bond id="b5" atomRefs2="a5 a6" order="2">
<bondStereo>C</bondStereo>
</bond>
<bond id="b6" atomRefs2="a1 a6" order="1" />
</bondArray>
</molecule>
```
=> Fix crash on specific CML format

src/graphsym.cpp
ASAN reported integer overflow. Since the integers there are unsigned, convert m to unsigned as well.
=> Fix ASAN reported integer overflow

.github/workflows/cifuzz.yml
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz where Open Babel already runs (https://github.com/google/oss-fuzz/tree/master/projects/openbabel). CIFuzz can help detect regressions and moves the fuzzing a bit further into the development pipeline, and has a variety of features (see the URL above). In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.
=> ci: add CIFuzz Github Action

CMakeLists.txt
IntelLLVM, icpx, does not support `-ipo` with argument
fix #2715
=> build(intel): use CMake IPO and strip at linkage for Release build

src/mol.cpp
I'm not certain that this is a proper fix for this issue, so perhaps someone can take a look.
Here's the CML file it crashes on (attempting to convert this CML to InChi:
```xml
<?xml version="1.0"?>
<cml>
<MDocument>
<MChemicalStruct>
<molecule molID="m1" absStereo="true">
<atomArray atomID="a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 a11 a12 a13 a14 a15 a16 a17 a18 a19 a20 a21 a22 a23 a24 a25 a26 a27 a28 a29 a30 a31 a32 a33 a34 a35 a36 a37 a38 a39 a40 a41 a42 a43 a44 a45 a46 a47 a48 a49 a50 a51 a52 a53 a54 a55 a56 a57 a58 a59 a60" elementType="C O C C O C C O C C O C C O C C O C C N C C O C C C C C O C O C O C C O C C C C O O C C C C C C C C O C C C C C R R R R" mrvMap="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 …
```
=> Fix crash when converting some bad CML to inchi
