openbabel/openbabel

- scripts/python/pybel.py
Make _repr_* methods operate on clones of molecules instead of actual molecules. This prevents changes introduced by displaying molecules in ipython notebook.
> Prevent ipython notebook from modifying molecules' coords.

- CMakeLists.txt
This matches the name in src/formats/...
> Correct name of inchi library

- src/formats/mol2format.cpp
An option to parse comments provided by UCSF Dock and Chimera. Mol2 writer is also capable to write properties from other sources, like SDF.
Example of such comments:
```
##########	Name:	ZINC04087362
##########	HA_RMSDs:	10.5487
##########	HA_RMSDh:	10.5466
##########	HA_RMSDm:	5.8751
##########	Cluster Size:	19
##########	Grid Score:	-45.986282
##########	Grid_vdw:	-38.770088
##########	Grid_es:	-7.216196
##########	Int_energy:	9.837175
@<TRIPOS>MOLECULE
ZINC04087362
....
```
Note:
There is a bug, although I'm not proficient enough in C to fix that - if N molecules are skipped using "-l" option, then comments for first molecule are lost. I guess MOL2Format::SkipObjects needs to check if line "m-2" has # at the beginning, and then skip few lines back (until hashed lines finish).
> Read and write UCSF Dock docking scores from comments

- include/openbabel/plugin.h
- src/formats/CMakeLists.txt
- src/formats/aoforceformat.cpp
- src/formats/formats.cmake
- src/plugin.cpp
aoforce files are generated from vibrational analyses with TurboMole.
> aoforce format

- scripts/ruby/extconf.rb
Substitute obsolete Config constant with RbConfig constant.
> Config -> RbConfig

- scripts/python/pybel.py
This is a quick fix for #129 that doesn't cause any breaking changes. The `_repr_svg_` method cleans up the svg returned by svgformat.c before passing along to ipython. Here's it working:
> svg ipython quick fix

- src/formats/vaspformat.cpp
> Fix #152 by adding missing header required for MSVC

- data/phmodel.txt
Contribution from Stefano Forli
> Added rule for protonating phosphonate groups (e.g., 1a0q).

- src/formats/pointcloudformat.cpp
> Fix #163 by using std::rand() instead of random()

- CMakeLists.txt
- test/rotortest.cpp
Add -march=native option. Can be turned off by -DOPTIMIZE_NATIVE=OFF.
See issue #184
> Add support for hardware popcount

- src/charges/eqeq.cpp
- src/charges/eqeq.h
Replaced convoluted logic with a simple flag check.
Builds and runs on my computer, and should fix #173.
> Fix for #173

- src/formats/mmcifformat.cpp
Formal oxidation is implemented.
> mmcifformat plugin now support atoms occupancy and atom_type category

- include/openbabel/depict/asciipainter.h
- include/openbabel/depict/cairopainter.h
- include/openbabel/depict/commandpainter.h
- include/openbabel/depict/depict.h
- include/openbabel/depict/painter.h
- include/openbabel/depict/svgpainter.h
- src/depict/asciipainter.cpp
- src/depict/cairopainter.cpp
- src/depict/commandpainter.cpp
- src/depict/depict.cpp
- src/depict/svgpainter.cpp
- src/formats/svgformat.cpp
Create ball and stick depiction with -xS option to SVG output.
> Ballandstick depict

- include/openbabel/depict/asciipainter.h
- include/openbabel/depict/cairopainter.h
- include/openbabel/depict/commandpainter.h
- include/openbabel/depict/painter.h
- include/openbabel/depict/svgpainter.h
- src/depict/asciipainter.cpp
- src/depict/cairopainter.cpp
- src/depict/commandpainter.cpp
- src/depict/depict.cpp
- src/depict/svgpainter.cpp
- src/formats/svgformat.cpp
Particularly improves the pseudo-3D SVG ball-and-stick depiction.
> Add support for opacity (not yet used) and perspective.

- include/openbabel/chargemodel.h
- include/openbabel/plugin.h
- src/CMakeLists.txt
- src/charges/fromfile.cpp
- src/ops/partialcharges.cpp
- src/plugin.cpp
From MJ Harvey - replaces #168
> Readcharges fromfile

- src/formats/svgformat.cpp
Just a simple addition of documentation for the SVG format.
> Adds documentation to ball and stick depicition of SVG format.

- src/formats/svgformat.cpp
This patch hopefully fixes #219
> Do not delete molecule in SVGFormat::WriteMolecule

- src/obutil.cpp
The ob_make_rmat function in /src/obutil.cpp contained an error in which the resulting orthonormal vectors for the transform were incorrectly normalised (in each case, the x component was divided 3 times by the magnitude of the vector, instead of each component being divided once).
I have also commented this function quite heavily to explain what it is doing, having worked through it to check I was correct.
Steve
> Fixed bug in ob_make_rmat in /src/obutil.cpp

- src/CMakeLists.txt
- src/fingerprints/fingerecfp.cpp
Donated by Noel O'Boyle and Roger Sayle of NextMove.
> Initial implementation of ECFP fingerprints.

- CMakeLists.txt
- src/formats/formats.cmake
Some changes need to compile with:
-DBUILD_SHARED=OFF -DWITH_INCHI=ON -DWITH_STATIC_INCHI=ON
> Allow compilation as static binaries

- src/formats/daltonformat.cpp
* Adds basic support for ATOMBASIS format
in both reading and writing
* make the plugin more compliant in terms of
default options (and obey those rules), i.e.
the -xb and -xs options
* Adds option (using -xk flag) to specify what
basis set to use. I got tired of having to
sed my way through thousands of input files.
> Overhaul of the DALTON format

- src/ops/partialcharges.cpp
Prints atomic partial charges on standard output after calculating them
> Add a --print option to the partial charge methods

- src/formats/vaspformat.cpp
https://github.com/openbabel/openbabel/pull/188
> VASP Write. "w" and "z" options.

- src/formats/mdlformat.cpp
By specifiying the option 'E' on writing, an "ASCII Depiction" property will be added to each entry in an SDF file. This contains an ASCII depiction of width 79.
There is probably not a burning need for this feature, but if present, it might be of use to some people and is pretty neat.
> Add an option to the MDL format writer to include an ASCII depiction

- scripts/openbabel-python.i
> [MRG] Support Python 2.x Unicode

- include/openbabel/bond.h
- src/bond.cpp
- src/mol.cpp
- src/rotor.cpp
Code modifications in response to @baoilleach comments on #331 for your consideration.
> enable sampleRingBonds option in IsRotor as well

- src/formats/jaguarformat.cpp
This change add support for converting Jaguar input files to other formats.  i.e. it adds READ support for Jaguar input files.
I didn't know how to update the tests for this feature.  Please let me know how to do this if needed.  Thanks.
> Add support for reading Jaguar input files to jaguarformat.cpp

- src/depict/depict.cpp
- src/depict/svgpainter.cpp
> Improve svg ball and stick

- data/phmodel.txt
Added an entry for the -NO2 group to preserve the explicit charge localization [N+](=O)[O-] when adding hydrogens at specific pH.
> Added line for -NO2 group

- .github/ISSUE_TEMPLATE.md
https://help.github.com/articles/creating-an-issue-template-for-your-repository/
> Add a default issue template for Open Babel - Suggestions welcome

- scripts/openbabel-python.i
Refer to issues #1551, #1552, and closed pull request #1553.
> Ignore some non-functioning python SWIG bindings.

- scripts/openbabel-python.i
Added a fix for OBMolAtomIter behavior in Python3.
> Added fix for OBMolAtomBFSIter in Python3

- src/formats/inchiformat.cpp
It turns out that the part of the InChI writer that handles the stereo assumes that AtomIds are simply AtomIdxs-1, but this is not true in general, and can lead to an incorrect stereo layer. The fix is to properly convert from AtomIds to AtomIdxs.
Although this only affects 11 molecules in ChEMBL when converting straight from SMI to InChI (and so wouldn't have been noticed before), it was already causing my second RInChI test case to fail (a test case taken from the RInChI docs). My guess is that it must be copying the molecule when generating the shared pointer, thus rearranging either the Ids or Idxs.
To be honest, I'm not 100% convinced that we need AtomIds - I must talk to Tim about this sometime.
> Correct handling of stereo when writing InChIs

- src/formats/rsmiformat.cpp
- test/testbabel.py
This is a repeat of #1655 after there was a merge conflict and I messed up git.
> Allow RSMI format to read partial reactions (Take 2)

- src/formats/rxnformat.cpp
- test/testbabel.py
This is an updated pull request for #1656 that fixes the test failures when it was merged after #1640.
> Add support for agents to RXN file format (Take 2)

- src/formats/vaspformat.cpp
There was a semicolon at the end of the 'if' statement
> Fix bug found due to MSVC warning

- scripts/python/pybel.py
Address #1615 by testing if filename is an instance of bytes and use a
bytes suffix in that case. This seems to be the approach used in cpython
source code, so I take it for being pythonic at the moment. (e.g.
https://github.com/python/cpython/blob/3f9183b/Lib/posixpath.py#L119 )
> use isinstance to test if filename is bytes

- src/fingerprint.cpp
If "folding" is requested for fingerprints from smaller to larger
bit sizes, simply extend the vector.
> Fix "folding" for fingerprints to larger bit sizes - #1654.

- doc/obdistgen.1
- doc/obrms.1
- doc/obsym.1
- doc/obtautomer.1
- doc/obthermo.1
> Adding missing manpags

- src/formats/tinkerformat.cpp
Resolves feature request #1732
`obabel -:'[C:345]([H:34])([H:34])([H:34])[C:234]([H:34])([H:34])[O:67]([H:68])' -otxyz -xc`
> Add support for using atom classes as Tinker atom types.

- src/distgeom.cpp
- src/forcefield.cpp
> Fix code error found from @baoilleach compiler warnings

- include/openbabel/data_utilities.h
- src/data_utilities.cpp
- src/formats/gaussformat.cpp
- tools/obthermo.cpp
tabs replaced by space for indentation
> Obthermo update patch

- src/formats/chemdrawcdx.cpp
[test-reaction-map.zip](https://github.com/openbabel/openbabel/files/1538600/test-reaction-map.zip)
This PR attempt to fix the following bug:
OpenBabel get Segfault while reading CDX contains such a reaction map like this: A -> B -> C (I expect to get the 2 reactions from the output: A->B and B->C). I include a simple CDX to test for this case (please rename it from `.zip` to `.cdx`).
> Read reaction map from ChemDraw CDX files

- src/formats/pngformat.cpp
- src/formats/yasaraformat.cpp
Fix #1689. Can you check @newbluemoon?
> Ensure portability to ARM platforms

- include/openbabel/generic.h
- src/formats/gaussformat.cpp
> Gaussformat reading multiple charge modles 2

- src/formats/moldenformat.cpp
Merging #344 caused a build failure as the API has changed for handling elements.
> Fix compile failure after recent Molden commit

- scripts/openbabel-ruby.i
Add ruby bindings for functions of `kekulize.h` , `obfunctions.h` and related header
> Add stereo + obfunctions + kekulize to ruby binding

- test/testbabel.py
- tools/obabel.cpp
> Fixes #1282: check format input is provided

- src/mcdlutil.cpp
See bts:
https://github.com/openbabel/openbabel/files/2081924/bt.txt
https://github.com/openbabel/openbabel/files/2082051/bt1.txt
> Fixes #1851: check some limits when converting smi to sdf using --gen2D

- tools/CMakeLists.txt
- tools/obmm.cpp
(Useful for Avogadro2 and Jupyter energies, etc.)
> Rebuild OBMM tool for interactive MM optimization

- src/config.h.cmake
> define isfinite removed.

- CMakeLists.txt
- data/CMakeLists.txt
- doc/CMakeLists.txt
This reverts commit 417361bb9f19c78434b067293980085464760c20.
This fixes #310.
> Revert "CMakeLists.txt: Allow configuring BABEL_DATADIR"

- src/mcdlutil.cpp
- test/testbindings.py
Should fix #1900 while keeping #1851 running.
A bit hacky though since the mcdlutil routines are hard to penetrate... If the original contributors have a better solution I'm all ears!
I also added tests for both #1851 and #1900
> Updated the coordinate generation from templates. 

- src/parsmart.cpp
This pull request should fix #1869.
> Fix memory leak in OBSmartsPattern::Init()

- tools/CMakeLists.txt
- tools/obrms.cpp
This provides significantly more functionality to obrms, including the ability to calculate the minimum rms and different options for handling files
> enhancements to obrms to support optimization of pose alignment

- doc/babel.1
- doc/babel.html
- src/formats/gausscubeformat.cpp
- src/formats/gaussformat.cpp
- src/formats/gausszmatformat.cpp
- tools/babel.cpp
- tools/obabel.cpp
- comment out route section of outputted Gaussian input
- add missing `gzmat` format
- update URLs
> Update Gaussian format

- doc/obrms.1
- tools/obrms.cpp
This provides an updated manpage and a bugfix.
> Obrms enhancement

- src/formats/fpsformat.cpp
Issue https://github.com/openbabel/openbabel/issues/1990 fix.
> fpsformat.cpp: compile bugfix header added.

- doc/babel.1
- doc/obchiral.1
- doc/obconformer.1
- doc/obdistgen.1
- doc/obenergy.1
- doc/obfit.1
- doc/obfit.html
- doc/obgen.1
- doc/obgrep.1
- doc/obminimize.1
- doc/obprobe.1
- doc/obprop.1
- doc/obrms.1
- doc/obrotamer.1
- doc/obrotate.1
- doc/obrotate.html
- doc/obspectrophore.1
- doc/obsym.1
- doc/obtautomer.1
- doc/obthermo.1
- doc/roundtrip.1
- Fix "SEE ALSO"
- replace `babel` with `obabel`
- fix self-reference
- Remove leading/trailing white spaces
- Other minor fixes
> Update doc [skip ci]

- README.md
I don't know why, but obviously the sourceforge does not have the latest version (3.0.0).
> update download link

- src/elements.cpp
- test/testbindings.py
Fixes #2063....I believe. Let me test this directly before this is merged.
> Bring back support for lowercase elements and D/T in GetAtomicNum().

- src/formats/mmcifformat.cpp
https://github.com/openbabel/openbabel/issues/2125
FYI @afonari
> Fix issue #2125

- include/openbabel/builder.h
- include/openbabel/forcefield.h
- include/openbabel/mcdlutil.h
- src/canon.cpp
- src/formats/smilesformat.cpp
- src/mcdlutil.cpp
Context: https://github.com/openbabel/openbabel/pull/2163#pullrequestreview-390408710.
attn @ghutchis
> Follow-up with missing spelling fixes from #2163

- .github/release-drafter.yml
Drafts initial release notes based on pull request merges
https://probot.github.io/apps/release-drafter/
> Add a template to use with the release drafter GH app

- tools/obenergy.cpp
- check if input file is passed to avoid SEGV
- remove unused variables
- clang-format
> Improve tools/obenergy.cpp

- src/spectrophore.cpp
See related https://github.com/openbabel/openbabel/pull/2220.
> Fix memory leak in spectrophore.cpp

- src/parsmart.cpp
- test/smartstest.cpp
See related https://github.com/openbabel/openbabel/pull/2220
> Fix memory leaks in parsmart.cpp and smartstest.cpp

- scripts/openbabel-R.i
- scripts/openbabel-csharp.i
- scripts/openbabel-java.i
- scripts/openbabel-mono.i
- scripts/openbabel-perl.i
- scripts/openbabel-php.i
- scripts/openbabel-python.i
- scripts/openbabel-ruby.i
- test/testbindings.py
Include kekulize.h in bindings so you can run OBKekulize.
> Resolve Issue #1999

- src/formats/formats.cmake
- src/formats/json/chemicaljsonformat.cpp
Supports atoms / bonds, coordinate sets, vibrations and charges
> Initial support for Avogadro's ChemicalJSON (.cjson)

- src/conformersearch.cpp
change std::cout to m_logstream for better output write control
> fix verbose stdout write of GetConformers

- scripts/python/examples/dalke_test.py
- scripts/python/examples/testpybel.py
- test/testbabel.py
- test/testbindings.py
- test/testcdjsonformat.py
- test/testobconv_writers.py
- test/testpcjsonformat.py
- test/testroundtrip.py
- fix misuse of `unittest.TestCase.assert_`
- improve usages of `unitest.TestCase` methods
> test(python): improvements

- scripts/python/examples/testpybel.py
- scripts/python/openbabel/pybel.py
- scripts/python/setup.py
- test/testbindings.py
https://peps.python.org/pep-3151/
> python: replace IOError with OSError

- src/formats/json/chemicaljsonformat.cpp
> Add support for NMR and electronic spectra in CJSON

- .github/workflows/build_cmake.yml
- data/CMakeLists.txt
> Fix Windows build - require Perl binary to build

- CMakeLists.txt
- cmake/cmake_uninstall.cmake.in
https://cmake.org/cmake/help/v3.1/command/exec_program.html
> replace deprecated `exec_program` with `execute_process` and fix syntax error

- src/formats/json/chemicaljsonformat.cpp
> Read and write total charge and spin multiplicity when available

- doc/obabel.1
- doc/obchiral.1
- doc/obconformer.1
- doc/obdistgen.1
- doc/obenergy.1
- doc/obfit.1
- doc/obgen.1
- doc/obgrep.1
- doc/obgui.1
- doc/obminimize.1
- doc/obprobe.1
- doc/obprop.1
- doc/obrms.1
- doc/obrotamer.1
- doc/obrotate.1
- doc/obspectrophore.1
- doc/obsym.1
- doc/obtautomer.1
- doc/obthermo.1
- doc/roundtrip.1
- add missing formats to obabel.1
- remove unnecessary space between flag and argument
- quotation is not mandatory (but strongly recommended) in `-:"SMILES-string"` for `obabel`
- improve roff stuffs and fix typos
> doc: update man

- src/formats/orcaformat.cpp
> Tweak vibration reading for Orca 5, which adds header lines

- doc/obminimize.1
- doc/obminimize.html
- tools/obminimize.cpp
Update the obminimize help message to include the "-o format" option and add the full option list to the man page and html documentation.
> Update obminimize help message & docs

- .github/workflows/lint_python.yml
Using this branch to change the runner for automated testing on babel, updating the python version in hopes to resolve the security checks
> updated runner python setup

- src/confsearch.cpp
- src/formats/fchkformat.cpp
- src/formats/vaspformat.cpp
> refactor: remove deprecated std::bind2nd

- src/formats/vaspformat.cpp
- add WRITEONEONLY to Flags
- expand indentation tab
- fix alignment
> fix: vaspformat

- src/formats/pdbqtformat.cpp
Fixes issue https://github.com/openbabel/openbabel/issues/2595
> Fixed alignment of partial charges for PDBQT-files

- test/testbabel.py
- tools/obrms.cpp
Add timeout option (necessary for mols with many symmetries) and fix bug with default behavior (was not doing one to one mappings).  Also, added test.
> obrms improvements

- src/formats/fastaformat.cpp
(Useful for Avogadro "insert DNA" command)
> Ensure chains and residues are retained in FASTA generation
